// Code generated by mojo. DO NOT EDIT.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mojo/db/config.proto
// Protobuf Java Version: 4.33.4

package org.mojolang.mojo.db;

@com.google.protobuf.Generated
public final class ConfigProto extends com.google.protobuf.GeneratedFile {
  private ConfigProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "ConfigProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_Config_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mojo_db_Config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024mojo/db/config.proto\022\007mojo.db\032\024mojo/co" +
      "re/time.proto\"\272\003\n\006Config\022\016\n\006driver\030\001 \001(\t" +
      "\022\013\n\003dsn\030\002 \001(\t\022\r\n\005debug\030\003 \001(\010\022\034\n\024max_idle" +
      "_connections\030\004 \001(\005\022\034\n\024max_open_connectio" +
      "ns\030\005 \001(\005\0222\n\025connection_keep_alive\030\006 \001(\0132" +
      "\023.mojo.core.Duration\022/\n\022slow_log_thresho" +
      "ld\030\007 \001(\0132\023.mojo.core.Duration\022\025\n\renable_" +
      "metric\030\010 \001(\010\022\024\n\014enable_trace\030\t \001(\010\022\031\n\021en" +
      "able_detail_sql\030\n \001(\010\022\031\n\021enable_log_acce" +
      "ss\030\013 \001(\010\022!\n\031enable_log_access_request\030\014 " +
      "\001(\010\022\"\n\032enable_log_access_response\030\r \001(\010\022" +
      "\033\n\023default_string_size\030\016 \001(\004\022\034\n\024disable_" +
      "auto_migrate\030\024 \001(\010BR\n\024org.mojolang.mojo." +
      "dbB\013ConfigProtoP\001Z+github.com/mojo-lang/" +
      "mojo/go/pkg/mojo/db;dbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.core.TimeProto.getDescriptor(),
        });
    internal_static_mojo_db_Config_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mojo_db_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mojo_db_Config_descriptor,
        new java.lang.String[] { "Driver", "Dsn", "Debug", "MaxIdleConnections", "MaxOpenConnections", "ConnectionKeepAlive", "SlowLogThreshold", "EnableMetric", "EnableTrace", "EnableDetailSql", "EnableLogAccess", "EnableLogAccessRequest", "EnableLogAccessResponse", "DefaultStringSize", "DisableAutoMigrate", });
    descriptor.resolveAllFeaturesImmutable();
    org.mojolang.mojo.core.TimeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
