// Code generated by mojo. DO NOT EDIT.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mojo/db/sql/data_type.proto
// Protobuf Java Version: 4.33.4

package org.mojolang.mojo.db.sql;

@com.google.protobuf.Generated
public final class DataTypeProto extends com.google.protobuf.GeneratedFile {
  private DataTypeProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "DataTypeProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_DataType_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mojo_db_sql_DataType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033mojo/db/sql/data_type.proto\022\013mojo.db.s" +
      "ql\"\030\n\010DataType\022\014\n\004name\030\001 \001(\tB]\n\030org.mojo" +
      "lang.mojo.db.sqlB\rDataTypeProtoP\001Z0githu" +
      "b.com/mojo-lang/mojo/go/pkg/mojo/db/sql;" +
      "sqlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mojo_db_sql_DataType_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mojo_db_sql_DataType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mojo_db_sql_DataType_descriptor,
        new java.lang.String[] { "Name", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
