// Code generated by mojo. DO NOT EDIT.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mojo/db/sql/delete_stmt.proto
// Protobuf Java Version: 4.33.4

package org.mojolang.mojo.db.sql;

@com.google.protobuf.Generated
public final class DeleteStmtProto extends com.google.protobuf.GeneratedFile {
  private DeleteStmtProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "DeleteStmtProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_DeleteStmt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mojo_db_sql_DeleteStmt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035mojo/db/sql/delete_stmt.proto\022\013mojo.db" +
      ".sql\032(mojo/db/sql/data_manipulation_stmt" +
      ".proto\032&mojo/db/sql/qualified_table_name" +
      ".proto\032\"mojo/db/sql/returning_clause.pro" +
      "to\032\025mojo/db/sql/sql.proto\032\024mojo/lang/lan" +
      "g.proto\"\272\002\n\nDeleteStmt\022+\n\016start_position" +
      "\030\001 \001(\0132\023.mojo.lang.Position\022)\n\014end_posit" +
      "ion\030\002 \001(\0132\023.mojo.lang.Position\022\014\n\004kind\030\004" +
      " \001(\003\022\020\n\010implicit\030\005 \001(\010\022%\n\004with\030\n \001(\0132\027.m" +
      "ojo.db.sql.WithClause\0223\n\ntable_name\030\013 \001(" +
      "\0132\037.mojo.db.sql.QualifiedTableName\022\'\n\005wh" +
      "ere\030\014 \001(\0132\030.mojo.db.sql.WhereClause\022/\n\tr" +
      "eturning\030\017 \001(\0132\034.mojo.db.sql.ReturningCl" +
      "auseB_\n\030org.mojolang.mojo.db.sqlB\017Delete" +
      "StmtProtoP\001Z0github.com/mojo-lang/mojo/g" +
      "o/pkg/mojo/db/sql;sqlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.db.sql.DataManipulationStmtProto.getDescriptor(),
          org.mojolang.mojo.db.sql.QualifiedTableNameProto.getDescriptor(),
          org.mojolang.mojo.db.sql.ReturningClauseProto.getDescriptor(),
          org.mojolang.mojo.db.sql.SqlProto.getDescriptor(),
          org.mojolang.mojo.lang.LangProto.getDescriptor(),
        });
    internal_static_mojo_db_sql_DeleteStmt_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mojo_db_sql_DeleteStmt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mojo_db_sql_DeleteStmt_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "With", "TableName", "Where", "Returning", });
    descriptor.resolveAllFeaturesImmutable();
    org.mojolang.mojo.db.sql.DataManipulationStmtProto.getDescriptor();
    org.mojolang.mojo.db.sql.QualifiedTableNameProto.getDescriptor();
    org.mojolang.mojo.db.sql.ReturningClauseProto.getDescriptor();
    org.mojolang.mojo.db.sql.SqlProto.getDescriptor();
    org.mojolang.mojo.lang.LangProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
