// Code generated by mojo. DO NOT EDIT.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mojo/db/sql/partition_clause.proto
// Protobuf Java Version: 4.33.4

package org.mojolang.mojo.db.sql;

@com.google.protobuf.Generated
public final class PartitionClauseProto extends com.google.protobuf.GeneratedFile {
  private PartitionClauseProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 4,
      /* suffix= */ "",
      "PartitionClauseProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_PartitionClause_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mojo_db_sql_PartitionClause_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"mojo/db/sql/partition_clause.proto\022\013mo" +
      "jo.db.sql\032\030mojo/db/sql/clause.proto\032\025moj" +
      "o/db/sql/sql.proto\032\024mojo/lang/lang.proto" +
      "\"\267\001\n\017PartitionClause\022+\n\016start_position\030\001" +
      " \001(\0132\023.mojo.lang.Position\022)\n\014end_positio" +
      "n\030\002 \001(\0132\023.mojo.lang.Position\022\014\n\004kind\030\004 \001" +
      "(\003\022\020\n\010implicit\030\005 \001(\010\022,\n\013expressions\030\n \003(" +
      "\0132\027.mojo.db.sql.ExpressionBd\n\030org.mojola" +
      "ng.mojo.db.sqlB\024PartitionClauseProtoP\001Z0" +
      "github.com/mojo-lang/mojo/go/pkg/mojo/db" +
      "/sql;sqlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.db.sql.ClauseProto.getDescriptor(),
          org.mojolang.mojo.db.sql.SqlProto.getDescriptor(),
          org.mojolang.mojo.lang.LangProto.getDescriptor(),
        });
    internal_static_mojo_db_sql_PartitionClause_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_mojo_db_sql_PartitionClause_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_mojo_db_sql_PartitionClause_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", "Expressions", });
    descriptor.resolveAllFeaturesImmutable();
    org.mojolang.mojo.db.sql.ClauseProto.getDescriptor();
    org.mojolang.mojo.db.sql.SqlProto.getDescriptor();
    org.mojolang.mojo.lang.LangProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
