// Code generated by mojo. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.2
// source: mojo/geom/feature_collection.proto

package geom

import (
	core "github.com/mojo-lang/mojo/packages/core/go/pkg/mojo/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FeatureCollection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     string        `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Features []*Feature    `protobuf:"bytes,5,rep,name=features,proto3" json:"features,omitempty"`
	Keys     []string      `protobuf:"bytes,13,rep,name=keys,proto3" json:"keys,omitempty"`
	Values   []*core.Value `protobuf:"bytes,14,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *FeatureCollection) Reset() {
	*x = FeatureCollection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mojo_geom_feature_collection_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeatureCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureCollection) ProtoMessage() {}

func (x *FeatureCollection) ProtoReflect() protoreflect.Message {
	mi := &file_mojo_geom_feature_collection_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureCollection.ProtoReflect.Descriptor instead.
func (*FeatureCollection) Descriptor() ([]byte, []int) {
	return file_mojo_geom_feature_collection_proto_rawDescGZIP(), []int{0}
}

func (x *FeatureCollection) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FeatureCollection) GetFeatures() []*Feature {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *FeatureCollection) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *FeatureCollection) GetValues() []*core.Value {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_mojo_geom_feature_collection_proto protoreflect.FileDescriptor

var file_mojo_geom_feature_collection_proto_rawDesc = []byte{
	0x0a, 0x22, 0x6d, 0x6f, 0x6a, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x6d, 0x2f, 0x66, 0x65, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x6c, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x6f, 0x6a, 0x6f, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x1a,
	0x15, 0x6d, 0x6f, 0x6a, 0x6f, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x6d, 0x6f, 0x6a, 0x6f, 0x2f, 0x67, 0x65, 0x6f,
	0x6d, 0x2f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x95, 0x01, 0x0a, 0x11, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x6f,
	0x6a, 0x6f, 0x2e, 0x67, 0x65, 0x6f, 0x6d, 0x2e, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x08, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x65, 0x79,
	0x73, 0x18, 0x0d, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x12, 0x28, 0x0a,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x0e, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6d, 0x6f, 0x6a, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x63, 0x0a, 0x16, 0x6f, 0x72, 0x67, 0x2e, 0x6d,
	0x6f, 0x6a, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2e, 0x6d, 0x6f, 0x6a, 0x6f, 0x2e, 0x67, 0x65, 0x6f,
	0x6d, 0x42, 0x16, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x43, 0x6f, 0x6c, 0x6c, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2f, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6a, 0x6f, 0x2d, 0x6c, 0x61, 0x6e,
	0x67, 0x2f, 0x67, 0x65, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6d, 0x6f,
	0x6a, 0x6f, 0x2f, 0x67, 0x65, 0x6f, 0x6d, 0x3b, 0x67, 0x65, 0x6f, 0x6d, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mojo_geom_feature_collection_proto_rawDescOnce sync.Once
	file_mojo_geom_feature_collection_proto_rawDescData = file_mojo_geom_feature_collection_proto_rawDesc
)

func file_mojo_geom_feature_collection_proto_rawDescGZIP() []byte {
	file_mojo_geom_feature_collection_proto_rawDescOnce.Do(func() {
		file_mojo_geom_feature_collection_proto_rawDescData = protoimpl.X.CompressGZIP(file_mojo_geom_feature_collection_proto_rawDescData)
	})
	return file_mojo_geom_feature_collection_proto_rawDescData
}

var file_mojo_geom_feature_collection_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mojo_geom_feature_collection_proto_goTypes = []interface{}{
	(*FeatureCollection)(nil), // 0: mojo.geom.FeatureCollection
	(*Feature)(nil),           // 1: mojo.geom.Feature
	(*core.Value)(nil),        // 2: mojo.core.Value
}
var file_mojo_geom_feature_collection_proto_depIdxs = []int32{
	1, // 0: mojo.geom.FeatureCollection.features:type_name -> mojo.geom.Feature
	2, // 1: mojo.geom.FeatureCollection.values:type_name -> mojo.core.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mojo_geom_feature_collection_proto_init() }
func file_mojo_geom_feature_collection_proto_init() {
	if File_mojo_geom_feature_collection_proto != nil {
		return
	}
	file_mojo_geom_feature_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mojo_geom_feature_collection_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeatureCollection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mojo_geom_feature_collection_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mojo_geom_feature_collection_proto_goTypes,
		DependencyIndexes: file_mojo_geom_feature_collection_proto_depIdxs,
		MessageInfos:      file_mojo_geom_feature_collection_proto_msgTypes,
	}.Build()
	File_mojo_geom_feature_collection_proto = out.File
	file_mojo_geom_feature_collection_proto_rawDesc = nil
	file_mojo_geom_feature_collection_proto_goTypes = nil
	file_mojo_geom_feature_collection_proto_depIdxs = nil
}
