// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/sql.proto

package org.mojolang.mojo.db.sql;

/**
 * Protobuf type {@code mojo.db.sql.FromClause}
 */
public final class FromClause extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.db.sql.FromClause)
    FromClauseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FromClause.newBuilder() to construct.
  private FromClause(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FromClause() {
    tables_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FromClause();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_FromClause_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_FromClause_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.db.sql.FromClause.class, org.mojolang.mojo.db.sql.FromClause.Builder.class);
  }

  public static final int START_POSITION_FIELD_NUMBER = 1;
  private org.mojolang.mojo.lang.Position startPosition_;
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return Whether the startPosition field is set.
   */
  @java.lang.Override
  public boolean hasStartPosition() {
    return startPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return The startPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getStartPosition() {
    return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
  }
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
    return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
  }

  public static final int END_POSITION_FIELD_NUMBER = 2;
  private org.mojolang.mojo.lang.Position endPosition_;
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return Whether the endPosition field is set.
   */
  @java.lang.Override
  public boolean hasEndPosition() {
    return endPosition_ != null;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return The endPosition.
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.Position getEndPosition() {
    return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
  }
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
    return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
  }

  public static final int KIND_FIELD_NUMBER = 4;
  private long kind_ = 0L;
  /**
   * <code>int64 kind = 4;</code>
   * @return The kind.
   */
  @java.lang.Override
  public long getKind() {
    return kind_;
  }

  public static final int IMPLICIT_FIELD_NUMBER = 5;
  private boolean implicit_ = false;
  /**
   * <code>bool implicit = 5;</code>
   * @return The implicit.
   */
  @java.lang.Override
  public boolean getImplicit() {
    return implicit_;
  }

  public static final int TABLES_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private java.util.List<org.mojolang.mojo.db.sql.Table> tables_;
  /**
   * <code>repeated .mojo.db.sql.Table tables = 10;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.db.sql.Table> getTablesList() {
    return tables_;
  }
  /**
   * <code>repeated .mojo.db.sql.Table tables = 10;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.db.sql.TableOrBuilder> 
      getTablesOrBuilderList() {
    return tables_;
  }
  /**
   * <code>repeated .mojo.db.sql.Table tables = 10;</code>
   */
  @java.lang.Override
  public int getTablesCount() {
    return tables_.size();
  }
  /**
   * <code>repeated .mojo.db.sql.Table tables = 10;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.db.sql.Table getTables(int index) {
    return tables_.get(index);
  }
  /**
   * <code>repeated .mojo.db.sql.Table tables = 10;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.db.sql.TableOrBuilder getTablesOrBuilder(
      int index) {
    return tables_.get(index);
  }

  public static final int JOIN_FIELD_NUMBER = 11;
  private org.mojolang.mojo.db.sql.JoinClause join_;
  /**
   * <code>.mojo.db.sql.JoinClause join = 11;</code>
   * @return Whether the join field is set.
   */
  @java.lang.Override
  public boolean hasJoin() {
    return join_ != null;
  }
  /**
   * <code>.mojo.db.sql.JoinClause join = 11;</code>
   * @return The join.
   */
  @java.lang.Override
  public org.mojolang.mojo.db.sql.JoinClause getJoin() {
    return join_ == null ? org.mojolang.mojo.db.sql.JoinClause.getDefaultInstance() : join_;
  }
  /**
   * <code>.mojo.db.sql.JoinClause join = 11;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.db.sql.JoinClauseOrBuilder getJoinOrBuilder() {
    return join_ == null ? org.mojolang.mojo.db.sql.JoinClause.getDefaultInstance() : join_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startPosition_ != null) {
      output.writeMessage(1, getStartPosition());
    }
    if (endPosition_ != null) {
      output.writeMessage(2, getEndPosition());
    }
    if (kind_ != 0L) {
      output.writeInt64(4, kind_);
    }
    if (implicit_ != false) {
      output.writeBool(5, implicit_);
    }
    for (int i = 0; i < tables_.size(); i++) {
      output.writeMessage(10, tables_.get(i));
    }
    if (join_ != null) {
      output.writeMessage(11, getJoin());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartPosition());
    }
    if (endPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndPosition());
    }
    if (kind_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, kind_);
    }
    if (implicit_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, implicit_);
    }
    for (int i = 0; i < tables_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, tables_.get(i));
    }
    if (join_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getJoin());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.db.sql.FromClause)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.db.sql.FromClause other = (org.mojolang.mojo.db.sql.FromClause) obj;

    if (hasStartPosition() != other.hasStartPosition()) return false;
    if (hasStartPosition()) {
      if (!getStartPosition()
          .equals(other.getStartPosition())) return false;
    }
    if (hasEndPosition() != other.hasEndPosition()) return false;
    if (hasEndPosition()) {
      if (!getEndPosition()
          .equals(other.getEndPosition())) return false;
    }
    if (getKind()
        != other.getKind()) return false;
    if (getImplicit()
        != other.getImplicit()) return false;
    if (!getTablesList()
        .equals(other.getTablesList())) return false;
    if (hasJoin() != other.hasJoin()) return false;
    if (hasJoin()) {
      if (!getJoin()
          .equals(other.getJoin())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartPosition()) {
      hash = (37 * hash) + START_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getStartPosition().hashCode();
    }
    if (hasEndPosition()) {
      hash = (37 * hash) + END_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getEndPosition().hashCode();
    }
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getKind());
    hash = (37 * hash) + IMPLICIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getImplicit());
    if (getTablesCount() > 0) {
      hash = (37 * hash) + TABLES_FIELD_NUMBER;
      hash = (53 * hash) + getTablesList().hashCode();
    }
    if (hasJoin()) {
      hash = (37 * hash) + JOIN_FIELD_NUMBER;
      hash = (53 * hash) + getJoin().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.db.sql.FromClause parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.db.sql.FromClause parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.db.sql.FromClause prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.db.sql.FromClause}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.db.sql.FromClause)
      org.mojolang.mojo.db.sql.FromClauseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_FromClause_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_FromClause_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.db.sql.FromClause.class, org.mojolang.mojo.db.sql.FromClause.Builder.class);
    }

    // Construct using org.mojolang.mojo.db.sql.FromClause.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      startPosition_ = null;
      if (startPositionBuilder_ != null) {
        startPositionBuilder_.dispose();
        startPositionBuilder_ = null;
      }
      endPosition_ = null;
      if (endPositionBuilder_ != null) {
        endPositionBuilder_.dispose();
        endPositionBuilder_ = null;
      }
      kind_ = 0L;
      implicit_ = false;
      if (tablesBuilder_ == null) {
        tables_ = java.util.Collections.emptyList();
      } else {
        tables_ = null;
        tablesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      join_ = null;
      if (joinBuilder_ != null) {
        joinBuilder_.dispose();
        joinBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.db.sql.SqlProto.internal_static_mojo_db_sql_FromClause_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.db.sql.FromClause getDefaultInstanceForType() {
      return org.mojolang.mojo.db.sql.FromClause.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.db.sql.FromClause build() {
      org.mojolang.mojo.db.sql.FromClause result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.db.sql.FromClause buildPartial() {
      org.mojolang.mojo.db.sql.FromClause result = new org.mojolang.mojo.db.sql.FromClause(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.mojolang.mojo.db.sql.FromClause result) {
      if (tablesBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          tables_ = java.util.Collections.unmodifiableList(tables_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.tables_ = tables_;
      } else {
        result.tables_ = tablesBuilder_.build();
      }
    }

    private void buildPartial0(org.mojolang.mojo.db.sql.FromClause result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.startPosition_ = startPositionBuilder_ == null
            ? startPosition_
            : startPositionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.endPosition_ = endPositionBuilder_ == null
            ? endPosition_
            : endPositionBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.kind_ = kind_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.implicit_ = implicit_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.join_ = joinBuilder_ == null
            ? join_
            : joinBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.db.sql.FromClause) {
        return mergeFrom((org.mojolang.mojo.db.sql.FromClause)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.db.sql.FromClause other) {
      if (other == org.mojolang.mojo.db.sql.FromClause.getDefaultInstance()) return this;
      if (other.hasStartPosition()) {
        mergeStartPosition(other.getStartPosition());
      }
      if (other.hasEndPosition()) {
        mergeEndPosition(other.getEndPosition());
      }
      if (other.getKind() != 0L) {
        setKind(other.getKind());
      }
      if (other.getImplicit() != false) {
        setImplicit(other.getImplicit());
      }
      if (tablesBuilder_ == null) {
        if (!other.tables_.isEmpty()) {
          if (tables_.isEmpty()) {
            tables_ = other.tables_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureTablesIsMutable();
            tables_.addAll(other.tables_);
          }
          onChanged();
        }
      } else {
        if (!other.tables_.isEmpty()) {
          if (tablesBuilder_.isEmpty()) {
            tablesBuilder_.dispose();
            tablesBuilder_ = null;
            tables_ = other.tables_;
            bitField0_ = (bitField0_ & ~0x00000010);
            tablesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTablesFieldBuilder() : null;
          } else {
            tablesBuilder_.addAllMessages(other.tables_);
          }
        }
      }
      if (other.hasJoin()) {
        mergeJoin(other.getJoin());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getStartPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getEndPositionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 32: {
              kind_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 32
            case 40: {
              implicit_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 40
            case 82: {
              org.mojolang.mojo.db.sql.Table m =
                  input.readMessage(
                      org.mojolang.mojo.db.sql.Table.parser(),
                      extensionRegistry);
              if (tablesBuilder_ == null) {
                ensureTablesIsMutable();
                tables_.add(m);
              } else {
                tablesBuilder_.addMessage(m);
              }
              break;
            } // case 82
            case 90: {
              input.readMessage(
                  getJoinFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.mojolang.mojo.lang.Position startPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> startPositionBuilder_;
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return Whether the startPosition field is set.
     */
    public boolean hasStartPosition() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     * @return The startPosition.
     */
    public org.mojolang.mojo.lang.Position getStartPosition() {
      if (startPositionBuilder_ == null) {
        return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      } else {
        return startPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startPosition_ = value;
      } else {
        startPositionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (startPositionBuilder_ == null) {
        startPosition_ = builderForValue.build();
      } else {
        startPositionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder mergeStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          startPosition_ != null &&
          startPosition_ != org.mojolang.mojo.lang.Position.getDefaultInstance()) {
          getStartPositionBuilder().mergeFrom(value);
        } else {
          startPosition_ = value;
        }
      } else {
        startPositionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder clearStartPosition() {
      bitField0_ = (bitField0_ & ~0x00000001);
      startPosition_ = null;
      if (startPositionBuilder_ != null) {
        startPositionBuilder_.dispose();
        startPositionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getStartPositionBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getStartPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
      if (startPositionBuilder_ != null) {
        return startPositionBuilder_.getMessageOrBuilder();
      } else {
        return startPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getStartPositionFieldBuilder() {
      if (startPositionBuilder_ == null) {
        startPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getStartPosition(),
                getParentForChildren(),
                isClean());
        startPosition_ = null;
      }
      return startPositionBuilder_;
    }

    private org.mojolang.mojo.lang.Position endPosition_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> endPositionBuilder_;
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return Whether the endPosition field is set.
     */
    public boolean hasEndPosition() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     * @return The endPosition.
     */
    public org.mojolang.mojo.lang.Position getEndPosition() {
      if (endPositionBuilder_ == null) {
        return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      } else {
        return endPositionBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endPosition_ = value;
      } else {
        endPositionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (endPositionBuilder_ == null) {
        endPosition_ = builderForValue.build();
      } else {
        endPositionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder mergeEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          endPosition_ != null &&
          endPosition_ != org.mojolang.mojo.lang.Position.getDefaultInstance()) {
          getEndPositionBuilder().mergeFrom(value);
        } else {
          endPosition_ = value;
        }
      } else {
        endPositionBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder clearEndPosition() {
      bitField0_ = (bitField0_ & ~0x00000002);
      endPosition_ = null;
      if (endPositionBuilder_ != null) {
        endPositionBuilder_.dispose();
        endPositionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getEndPositionBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getEndPositionFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
      if (endPositionBuilder_ != null) {
        return endPositionBuilder_.getMessageOrBuilder();
      } else {
        return endPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      }
    }
    /**
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getEndPositionFieldBuilder() {
      if (endPositionBuilder_ == null) {
        endPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getEndPosition(),
                getParentForChildren(),
                isClean());
        endPosition_ = null;
      }
      return endPositionBuilder_;
    }

    private long kind_ ;
    /**
     * <code>int64 kind = 4;</code>
     * @return The kind.
     */
    @java.lang.Override
    public long getKind() {
      return kind_;
    }
    /**
     * <code>int64 kind = 4;</code>
     * @param value The kind to set.
     * @return This builder for chaining.
     */
    public Builder setKind(long value) {
      
      kind_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 kind = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      bitField0_ = (bitField0_ & ~0x00000004);
      kind_ = 0L;
      onChanged();
      return this;
    }

    private boolean implicit_ ;
    /**
     * <code>bool implicit = 5;</code>
     * @return The implicit.
     */
    @java.lang.Override
    public boolean getImplicit() {
      return implicit_;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @param value The implicit to set.
     * @return This builder for chaining.
     */
    public Builder setImplicit(boolean value) {
      
      implicit_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool implicit = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImplicit() {
      bitField0_ = (bitField0_ & ~0x00000008);
      implicit_ = false;
      onChanged();
      return this;
    }

    private java.util.List<org.mojolang.mojo.db.sql.Table> tables_ =
      java.util.Collections.emptyList();
    private void ensureTablesIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        tables_ = new java.util.ArrayList<org.mojolang.mojo.db.sql.Table>(tables_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.db.sql.Table, org.mojolang.mojo.db.sql.Table.Builder, org.mojolang.mojo.db.sql.TableOrBuilder> tablesBuilder_;

    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public java.util.List<org.mojolang.mojo.db.sql.Table> getTablesList() {
      if (tablesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tables_);
      } else {
        return tablesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public int getTablesCount() {
      if (tablesBuilder_ == null) {
        return tables_.size();
      } else {
        return tablesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public org.mojolang.mojo.db.sql.Table getTables(int index) {
      if (tablesBuilder_ == null) {
        return tables_.get(index);
      } else {
        return tablesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder setTables(
        int index, org.mojolang.mojo.db.sql.Table value) {
      if (tablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTablesIsMutable();
        tables_.set(index, value);
        onChanged();
      } else {
        tablesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder setTables(
        int index, org.mojolang.mojo.db.sql.Table.Builder builderForValue) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        tables_.set(index, builderForValue.build());
        onChanged();
      } else {
        tablesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder addTables(org.mojolang.mojo.db.sql.Table value) {
      if (tablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTablesIsMutable();
        tables_.add(value);
        onChanged();
      } else {
        tablesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder addTables(
        int index, org.mojolang.mojo.db.sql.Table value) {
      if (tablesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTablesIsMutable();
        tables_.add(index, value);
        onChanged();
      } else {
        tablesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder addTables(
        org.mojolang.mojo.db.sql.Table.Builder builderForValue) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        tables_.add(builderForValue.build());
        onChanged();
      } else {
        tablesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder addTables(
        int index, org.mojolang.mojo.db.sql.Table.Builder builderForValue) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        tables_.add(index, builderForValue.build());
        onChanged();
      } else {
        tablesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder addAllTables(
        java.lang.Iterable<? extends org.mojolang.mojo.db.sql.Table> values) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tables_);
        onChanged();
      } else {
        tablesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder clearTables() {
      if (tablesBuilder_ == null) {
        tables_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        tablesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public Builder removeTables(int index) {
      if (tablesBuilder_ == null) {
        ensureTablesIsMutable();
        tables_.remove(index);
        onChanged();
      } else {
        tablesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public org.mojolang.mojo.db.sql.Table.Builder getTablesBuilder(
        int index) {
      return getTablesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public org.mojolang.mojo.db.sql.TableOrBuilder getTablesOrBuilder(
        int index) {
      if (tablesBuilder_ == null) {
        return tables_.get(index);  } else {
        return tablesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.db.sql.TableOrBuilder> 
         getTablesOrBuilderList() {
      if (tablesBuilder_ != null) {
        return tablesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tables_);
      }
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public org.mojolang.mojo.db.sql.Table.Builder addTablesBuilder() {
      return getTablesFieldBuilder().addBuilder(
          org.mojolang.mojo.db.sql.Table.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public org.mojolang.mojo.db.sql.Table.Builder addTablesBuilder(
        int index) {
      return getTablesFieldBuilder().addBuilder(
          index, org.mojolang.mojo.db.sql.Table.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.db.sql.Table tables = 10;</code>
     */
    public java.util.List<org.mojolang.mojo.db.sql.Table.Builder> 
         getTablesBuilderList() {
      return getTablesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.db.sql.Table, org.mojolang.mojo.db.sql.Table.Builder, org.mojolang.mojo.db.sql.TableOrBuilder> 
        getTablesFieldBuilder() {
      if (tablesBuilder_ == null) {
        tablesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.db.sql.Table, org.mojolang.mojo.db.sql.Table.Builder, org.mojolang.mojo.db.sql.TableOrBuilder>(
                tables_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        tables_ = null;
      }
      return tablesBuilder_;
    }

    private org.mojolang.mojo.db.sql.JoinClause join_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.db.sql.JoinClause, org.mojolang.mojo.db.sql.JoinClause.Builder, org.mojolang.mojo.db.sql.JoinClauseOrBuilder> joinBuilder_;
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     * @return Whether the join field is set.
     */
    public boolean hasJoin() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     * @return The join.
     */
    public org.mojolang.mojo.db.sql.JoinClause getJoin() {
      if (joinBuilder_ == null) {
        return join_ == null ? org.mojolang.mojo.db.sql.JoinClause.getDefaultInstance() : join_;
      } else {
        return joinBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     */
    public Builder setJoin(org.mojolang.mojo.db.sql.JoinClause value) {
      if (joinBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        join_ = value;
      } else {
        joinBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     */
    public Builder setJoin(
        org.mojolang.mojo.db.sql.JoinClause.Builder builderForValue) {
      if (joinBuilder_ == null) {
        join_ = builderForValue.build();
      } else {
        joinBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     */
    public Builder mergeJoin(org.mojolang.mojo.db.sql.JoinClause value) {
      if (joinBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          join_ != null &&
          join_ != org.mojolang.mojo.db.sql.JoinClause.getDefaultInstance()) {
          getJoinBuilder().mergeFrom(value);
        } else {
          join_ = value;
        }
      } else {
        joinBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     */
    public Builder clearJoin() {
      bitField0_ = (bitField0_ & ~0x00000020);
      join_ = null;
      if (joinBuilder_ != null) {
        joinBuilder_.dispose();
        joinBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     */
    public org.mojolang.mojo.db.sql.JoinClause.Builder getJoinBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getJoinFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     */
    public org.mojolang.mojo.db.sql.JoinClauseOrBuilder getJoinOrBuilder() {
      if (joinBuilder_ != null) {
        return joinBuilder_.getMessageOrBuilder();
      } else {
        return join_ == null ?
            org.mojolang.mojo.db.sql.JoinClause.getDefaultInstance() : join_;
      }
    }
    /**
     * <code>.mojo.db.sql.JoinClause join = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.db.sql.JoinClause, org.mojolang.mojo.db.sql.JoinClause.Builder, org.mojolang.mojo.db.sql.JoinClauseOrBuilder> 
        getJoinFieldBuilder() {
      if (joinBuilder_ == null) {
        joinBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.db.sql.JoinClause, org.mojolang.mojo.db.sql.JoinClause.Builder, org.mojolang.mojo.db.sql.JoinClauseOrBuilder>(
                getJoin(),
                getParentForChildren(),
                isClean());
        join_ = null;
      }
      return joinBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.db.sql.FromClause)
  }

  // @@protoc_insertion_point(class_scope:mojo.db.sql.FromClause)
  private static final org.mojolang.mojo.db.sql.FromClause DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.db.sql.FromClause();
  }

  public static org.mojolang.mojo.db.sql.FromClause getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FromClause>
      PARSER = new com.google.protobuf.AbstractParser<FromClause>() {
    @java.lang.Override
    public FromClause parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FromClause> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FromClause> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.db.sql.FromClause getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

