// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/db/sql/procedural_stmt.proto

package org.mojolang.mojo.db.sql;

public final class ProceduralStmtProto {
  private ProceduralStmtProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_db_sql_ProceduralStmt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_db_sql_ProceduralStmt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!mojo/db/sql/procedural_stmt.proto\022\013moj" +
      "o.db.sql\032\024mojo/lang/lang.proto\"\210\001\n\016Proce" +
      "duralStmt\022+\n\016start_position\030\001 \001(\0132\023.mojo" +
      ".lang.Position\022)\n\014end_position\030\002 \001(\0132\023.m" +
      "ojo.lang.Position\022\014\n\004kind\030\004 \001(\003\022\020\n\010impli" +
      "cit\030\005 \001(\010Ba\n\030org.mojolang.mojo.db.sqlB\023P" +
      "roceduralStmtProtoP\001Z.github.com/mojo-la" +
      "ng/db/go/pkg/mojo/db/sql;sqlb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.lang.LangProto.getDescriptor(),
        });
    internal_static_mojo_db_sql_ProceduralStmt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_db_sql_ProceduralStmt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_db_sql_ProceduralStmt_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", });
    org.mojolang.mojo.lang.LangProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
