
type Operator {
    /// position of first character belonging to the Operator
    start_position: Position @1

    /// position of first character immediately after the Operator
    end_position:   Position @2

    /// Whether the Decl represents something directly written in source or
    /// it was implicitly generated by the type-checker.
    implicit: Bool @5
    
    symbol: String @11

    precedence: Int32 @12

    title: String @13
}
