// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/assignment_expr.proto

package org.mojolang.mojo.lang;

public final class AssignmentExprProto {
  private AssignmentExprProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mojo_lang_AssignmentExpr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mojo_lang_AssignmentExpr_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037mojo/lang/assignment_expr.proto\022\tmojo." +
      "lang\032\024mojo/lang/expr.proto\032\030mojo/lang/po" +
      "sition.proto\"\210\001\n\016AssignmentExpr\022+\n\016start" +
      "_position\030\001 \001(\0132\023.mojo.lang.Position\022)\n\014" +
      "end_position\030\002 \001(\0132\023.mojo.lang.Position\022" +
      "\014\n\004kind\030\003 \001(\005\022\020\n\010implicit\030\004 \001(\010B`\n\026org.m" +
      "ojolang.mojo.langB\023AssignmentExprProtoP\001" +
      "Z/github.com/mojo-lang/lang/go/pkg/mojo/" +
      "lang;langb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.mojolang.mojo.lang.ExprProto.getDescriptor(),
          org.mojolang.mojo.lang.PositionProto.getDescriptor(),
        });
    internal_static_mojo_lang_AssignmentExpr_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mojo_lang_AssignmentExpr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mojo_lang_AssignmentExpr_descriptor,
        new java.lang.String[] { "StartPosition", "EndPosition", "Kind", "Implicit", });
    org.mojolang.mojo.lang.ExprProto.getDescriptor();
    org.mojolang.mojo.lang.PositionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
