// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/lang.proto

package org.mojolang.mojo.lang;

public interface ObjectLiteralExprOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.lang.ObjectLiteralExpr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return Whether the startPosition field is set.
   */
  boolean hasStartPosition();
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   * @return The startPosition.
   */
  org.mojolang.mojo.lang.Position getStartPosition();
  /**
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder();

  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return Whether the endPosition field is set.
   */
  boolean hasEndPosition();
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   * @return The endPosition.
   */
  org.mojolang.mojo.lang.Position getEndPosition();
  /**
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder();

  /**
   * <code>int32 kind = 4;</code>
   * @return The kind.
   */
  int getKind();

  /**
   * <code>bool implicit = 5;</code>
   * @return The implicit.
   */
  boolean getImplicit();

  /**
   * <code>repeated .mojo.lang.ObjectLiteralExpr.Field fields = 20;</code>
   */
  java.util.List<org.mojolang.mojo.lang.ObjectLiteralExpr.Field> 
      getFieldsList();
  /**
   * <code>repeated .mojo.lang.ObjectLiteralExpr.Field fields = 20;</code>
   */
  org.mojolang.mojo.lang.ObjectLiteralExpr.Field getFields(int index);
  /**
   * <code>repeated .mojo.lang.ObjectLiteralExpr.Field fields = 20;</code>
   */
  int getFieldsCount();
  /**
   * <code>repeated .mojo.lang.ObjectLiteralExpr.Field fields = 20;</code>
   */
  java.util.List<? extends org.mojolang.mojo.lang.ObjectLiteralExpr.FieldOrBuilder> 
      getFieldsOrBuilderList();
  /**
   * <code>repeated .mojo.lang.ObjectLiteralExpr.Field fields = 20;</code>
   */
  org.mojolang.mojo.lang.ObjectLiteralExpr.FieldOrBuilder getFieldsOrBuilder(
      int index);
}
