// Code generated by mojo. DO NOT EDIT.

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mojo/core/integer.proto
// Protobuf Java Version: 4.33.4

package org.mojolang.mojo.core;

@com.google.protobuf.Generated
public interface NegativeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.Negative)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 val = 1;</code>
   * @return The val.
   */
  long getVal();
}
