// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/boxed.proto

package org.mojolang.mojo.core;

public interface Float32ValuesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.core.Float32Values)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated float vals = 1;</code>
   * @return A list containing the vals.
   */
  java.util.List<java.lang.Float> getValsList();
  /**
   * <code>repeated float vals = 1;</code>
   * @return The count of vals.
   */
  int getValsCount();
  /**
   * <code>repeated float vals = 1;</code>
   * @param index The index of the element to return.
   * @return The vals at the given index.
   */
  float getVals(int index);
}
