// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/core/error_details.proto

package org.mojolang.mojo.core;

/**
 * Protobuf type {@code mojo.core.MalformedRequest}
 */
public final class MalformedRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.core.MalformedRequest)
    MalformedRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MalformedRequest.newBuilder() to construct.
  private MalformedRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MalformedRequest() {
    fieldViolations_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MalformedRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.core.MalformedRequest.class, org.mojolang.mojo.core.MalformedRequest.Builder.class);
  }

  public interface FieldViolationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mojo.core.MalformedRequest.FieldViolation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string field = 1;</code>
     * @return The field.
     */
    java.lang.String getField();
    /**
     * <code>string field = 1;</code>
     * @return The bytes for field.
     */
    com.google.protobuf.ByteString
        getFieldBytes();

    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code mojo.core.MalformedRequest.FieldViolation}
   */
  public static final class FieldViolation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mojo.core.MalformedRequest.FieldViolation)
      FieldViolationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FieldViolation.newBuilder() to construct.
    private FieldViolation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FieldViolation() {
      field_ = "";
      description_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FieldViolation();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_FieldViolation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_FieldViolation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.core.MalformedRequest.FieldViolation.class, org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder.class);
    }

    public static final int FIELD_FIELD_NUMBER = 1;
    private volatile java.lang.Object field_;
    /**
     * <code>string field = 1;</code>
     * @return The field.
     */
    @java.lang.Override
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field_ = s;
        return s;
      }
    }
    /**
     * <code>string field = 1;</code>
     * @return The bytes for field.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 2;
    private volatile java.lang.Object description_;
    /**
     * <code>string description = 2;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 2;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(field_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, field_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, description_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(field_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, field_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, description_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mojolang.mojo.core.MalformedRequest.FieldViolation)) {
        return super.equals(obj);
      }
      org.mojolang.mojo.core.MalformedRequest.FieldViolation other = (org.mojolang.mojo.core.MalformedRequest.FieldViolation) obj;

      if (!getField()
          .equals(other.getField())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD_FIELD_NUMBER;
      hash = (53 * hash) + getField().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mojolang.mojo.core.MalformedRequest.FieldViolation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mojo.core.MalformedRequest.FieldViolation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mojo.core.MalformedRequest.FieldViolation)
        org.mojolang.mojo.core.MalformedRequest.FieldViolationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_FieldViolation_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_FieldViolation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mojolang.mojo.core.MalformedRequest.FieldViolation.class, org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder.class);
      }

      // Construct using org.mojolang.mojo.core.MalformedRequest.FieldViolation.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        field_ = "";

        description_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_FieldViolation_descriptor;
      }

      @java.lang.Override
      public org.mojolang.mojo.core.MalformedRequest.FieldViolation getDefaultInstanceForType() {
        return org.mojolang.mojo.core.MalformedRequest.FieldViolation.getDefaultInstance();
      }

      @java.lang.Override
      public org.mojolang.mojo.core.MalformedRequest.FieldViolation build() {
        org.mojolang.mojo.core.MalformedRequest.FieldViolation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mojolang.mojo.core.MalformedRequest.FieldViolation buildPartial() {
        org.mojolang.mojo.core.MalformedRequest.FieldViolation result = new org.mojolang.mojo.core.MalformedRequest.FieldViolation(this);
        result.field_ = field_;
        result.description_ = description_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mojolang.mojo.core.MalformedRequest.FieldViolation) {
          return mergeFrom((org.mojolang.mojo.core.MalformedRequest.FieldViolation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mojolang.mojo.core.MalformedRequest.FieldViolation other) {
        if (other == org.mojolang.mojo.core.MalformedRequest.FieldViolation.getDefaultInstance()) return this;
        if (!other.getField().isEmpty()) {
          field_ = other.field_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                field_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 18: {
                description_ = input.readStringRequireUtf8();

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object field_ = "";
      /**
       * <code>string field = 1;</code>
       * @return The field.
       */
      public java.lang.String getField() {
        java.lang.Object ref = field_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          field_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string field = 1;</code>
       * @return The bytes for field.
       */
      public com.google.protobuf.ByteString
          getFieldBytes() {
        java.lang.Object ref = field_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          field_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string field = 1;</code>
       * @param value The field to set.
       * @return This builder for chaining.
       */
      public Builder setField(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        field_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string field = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField() {
        
        field_ = getDefaultInstance().getField();
        onChanged();
        return this;
      }
      /**
       * <code>string field = 1;</code>
       * @param value The bytes for field to set.
       * @return This builder for chaining.
       */
      public Builder setFieldBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        field_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 2;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 2;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string description = 2;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mojo.core.MalformedRequest.FieldViolation)
    }

    // @@protoc_insertion_point(class_scope:mojo.core.MalformedRequest.FieldViolation)
    private static final org.mojolang.mojo.core.MalformedRequest.FieldViolation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mojolang.mojo.core.MalformedRequest.FieldViolation();
    }

    public static org.mojolang.mojo.core.MalformedRequest.FieldViolation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FieldViolation>
        PARSER = new com.google.protobuf.AbstractParser<FieldViolation>() {
      @java.lang.Override
      public FieldViolation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FieldViolation> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FieldViolation> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mojolang.mojo.core.MalformedRequest.FieldViolation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int FIELD_VIOLATIONS_FIELD_NUMBER = 1;
  private java.util.List<org.mojolang.mojo.core.MalformedRequest.FieldViolation> fieldViolations_;
  /**
   * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.core.MalformedRequest.FieldViolation> getFieldViolationsList() {
    return fieldViolations_;
  }
  /**
   * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.core.MalformedRequest.FieldViolationOrBuilder> 
      getFieldViolationsOrBuilderList() {
    return fieldViolations_;
  }
  /**
   * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
   */
  @java.lang.Override
  public int getFieldViolationsCount() {
    return fieldViolations_.size();
  }
  /**
   * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.MalformedRequest.FieldViolation getFieldViolations(int index) {
    return fieldViolations_.get(index);
  }
  /**
   * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.MalformedRequest.FieldViolationOrBuilder getFieldViolationsOrBuilder(
      int index) {
    return fieldViolations_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < fieldViolations_.size(); i++) {
      output.writeMessage(1, fieldViolations_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < fieldViolations_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, fieldViolations_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.core.MalformedRequest)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.core.MalformedRequest other = (org.mojolang.mojo.core.MalformedRequest) obj;

    if (!getFieldViolationsList()
        .equals(other.getFieldViolationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFieldViolationsCount() > 0) {
      hash = (37 * hash) + FIELD_VIOLATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldViolationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.core.MalformedRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.core.MalformedRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.core.MalformedRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.core.MalformedRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.core.MalformedRequest)
      org.mojolang.mojo.core.MalformedRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.core.MalformedRequest.class, org.mojolang.mojo.core.MalformedRequest.Builder.class);
    }

    // Construct using org.mojolang.mojo.core.MalformedRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (fieldViolationsBuilder_ == null) {
        fieldViolations_ = java.util.Collections.emptyList();
      } else {
        fieldViolations_ = null;
        fieldViolationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.core.ErrorDetailsProto.internal_static_mojo_core_MalformedRequest_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.core.MalformedRequest getDefaultInstanceForType() {
      return org.mojolang.mojo.core.MalformedRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.core.MalformedRequest build() {
      org.mojolang.mojo.core.MalformedRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.core.MalformedRequest buildPartial() {
      org.mojolang.mojo.core.MalformedRequest result = new org.mojolang.mojo.core.MalformedRequest(this);
      int from_bitField0_ = bitField0_;
      if (fieldViolationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          fieldViolations_ = java.util.Collections.unmodifiableList(fieldViolations_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fieldViolations_ = fieldViolations_;
      } else {
        result.fieldViolations_ = fieldViolationsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.core.MalformedRequest) {
        return mergeFrom((org.mojolang.mojo.core.MalformedRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.core.MalformedRequest other) {
      if (other == org.mojolang.mojo.core.MalformedRequest.getDefaultInstance()) return this;
      if (fieldViolationsBuilder_ == null) {
        if (!other.fieldViolations_.isEmpty()) {
          if (fieldViolations_.isEmpty()) {
            fieldViolations_ = other.fieldViolations_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldViolationsIsMutable();
            fieldViolations_.addAll(other.fieldViolations_);
          }
          onChanged();
        }
      } else {
        if (!other.fieldViolations_.isEmpty()) {
          if (fieldViolationsBuilder_.isEmpty()) {
            fieldViolationsBuilder_.dispose();
            fieldViolationsBuilder_ = null;
            fieldViolations_ = other.fieldViolations_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fieldViolationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFieldViolationsFieldBuilder() : null;
          } else {
            fieldViolationsBuilder_.addAllMessages(other.fieldViolations_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.mojolang.mojo.core.MalformedRequest.FieldViolation m =
                  input.readMessage(
                      org.mojolang.mojo.core.MalformedRequest.FieldViolation.parser(),
                      extensionRegistry);
              if (fieldViolationsBuilder_ == null) {
                ensureFieldViolationsIsMutable();
                fieldViolations_.add(m);
              } else {
                fieldViolationsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.mojolang.mojo.core.MalformedRequest.FieldViolation> fieldViolations_ =
      java.util.Collections.emptyList();
    private void ensureFieldViolationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fieldViolations_ = new java.util.ArrayList<org.mojolang.mojo.core.MalformedRequest.FieldViolation>(fieldViolations_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.core.MalformedRequest.FieldViolation, org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder, org.mojolang.mojo.core.MalformedRequest.FieldViolationOrBuilder> fieldViolationsBuilder_;

    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public java.util.List<org.mojolang.mojo.core.MalformedRequest.FieldViolation> getFieldViolationsList() {
      if (fieldViolationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fieldViolations_);
      } else {
        return fieldViolationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public int getFieldViolationsCount() {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.size();
      } else {
        return fieldViolationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public org.mojolang.mojo.core.MalformedRequest.FieldViolation getFieldViolations(int index) {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.get(index);
      } else {
        return fieldViolationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder setFieldViolations(
        int index, org.mojolang.mojo.core.MalformedRequest.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.set(index, value);
        onChanged();
      } else {
        fieldViolationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder setFieldViolations(
        int index, org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder addFieldViolations(org.mojolang.mojo.core.MalformedRequest.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(value);
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder addFieldViolations(
        int index, org.mojolang.mojo.core.MalformedRequest.FieldViolation value) {
      if (fieldViolationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(index, value);
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder addFieldViolations(
        org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder addFieldViolations(
        int index, org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder builderForValue) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldViolationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder addAllFieldViolations(
        java.lang.Iterable<? extends org.mojolang.mojo.core.MalformedRequest.FieldViolation> values) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fieldViolations_);
        onChanged();
      } else {
        fieldViolationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder clearFieldViolations() {
      if (fieldViolationsBuilder_ == null) {
        fieldViolations_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fieldViolationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public Builder removeFieldViolations(int index) {
      if (fieldViolationsBuilder_ == null) {
        ensureFieldViolationsIsMutable();
        fieldViolations_.remove(index);
        onChanged();
      } else {
        fieldViolationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder getFieldViolationsBuilder(
        int index) {
      return getFieldViolationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public org.mojolang.mojo.core.MalformedRequest.FieldViolationOrBuilder getFieldViolationsOrBuilder(
        int index) {
      if (fieldViolationsBuilder_ == null) {
        return fieldViolations_.get(index);  } else {
        return fieldViolationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.core.MalformedRequest.FieldViolationOrBuilder> 
         getFieldViolationsOrBuilderList() {
      if (fieldViolationsBuilder_ != null) {
        return fieldViolationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fieldViolations_);
      }
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder addFieldViolationsBuilder() {
      return getFieldViolationsFieldBuilder().addBuilder(
          org.mojolang.mojo.core.MalformedRequest.FieldViolation.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder addFieldViolationsBuilder(
        int index) {
      return getFieldViolationsFieldBuilder().addBuilder(
          index, org.mojolang.mojo.core.MalformedRequest.FieldViolation.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.core.MalformedRequest.FieldViolation field_violations = 1;</code>
     */
    public java.util.List<org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder> 
         getFieldViolationsBuilderList() {
      return getFieldViolationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.core.MalformedRequest.FieldViolation, org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder, org.mojolang.mojo.core.MalformedRequest.FieldViolationOrBuilder> 
        getFieldViolationsFieldBuilder() {
      if (fieldViolationsBuilder_ == null) {
        fieldViolationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.core.MalformedRequest.FieldViolation, org.mojolang.mojo.core.MalformedRequest.FieldViolation.Builder, org.mojolang.mojo.core.MalformedRequest.FieldViolationOrBuilder>(
                fieldViolations_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        fieldViolations_ = null;
      }
      return fieldViolationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.core.MalformedRequest)
  }

  // @@protoc_insertion_point(class_scope:mojo.core.MalformedRequest)
  private static final org.mojolang.mojo.core.MalformedRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.core.MalformedRequest();
  }

  public static org.mojolang.mojo.core.MalformedRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MalformedRequest>
      PARSER = new com.google.protobuf.AbstractParser<MalformedRequest>() {
    @java.lang.Override
    public MalformedRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MalformedRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MalformedRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.core.MalformedRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

