// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/import_decl.proto

package org.mojolang.mojo.lang;

public interface ImportDeclOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.lang.ImportDecl)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *&#47; position of first character belonging to the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  boolean hasStartPosition();
  /**
   * <pre>
   *&#47; position of first character belonging to the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  org.mojolang.mojo.lang.Position getStartPosition();
  /**
   * <pre>
   *&#47; position of first character belonging to the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder();

  /**
   * <pre>
   *&#47; position of first character immediately after the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  boolean hasEndPosition();
  /**
   * <pre>
   *&#47; position of first character immediately after the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  org.mojolang.mojo.lang.Position getEndPosition();
  /**
   * <pre>
   *&#47; position of first character immediately after the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder();

  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string package = 6;</code>
   */
  java.lang.String getPackage();
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string package = 6;</code>
   */
  com.google.protobuf.ByteString
      getPackageBytes();

  /**
   * <code>string import_package = 10;</code>
   */
  java.lang.String getImportPackage();
  /**
   * <code>string import_package = 10;</code>
   */
  com.google.protobuf.ByteString
      getImportPackageBytes();

  /**
   * <code>string import_package_alias = 11;</code>
   */
  java.lang.String getImportPackageAlias();
  /**
   * <code>string import_package_alias = 11;</code>
   */
  com.google.protobuf.ByteString
      getImportPackageAliasBytes();

  /**
   * <code>repeated .mojo.lang.ImportDecl.Identifier identifiers = 12;</code>
   */
  java.util.List<org.mojolang.mojo.lang.ImportDecl.Identifier> 
      getIdentifiersList();
  /**
   * <code>repeated .mojo.lang.ImportDecl.Identifier identifiers = 12;</code>
   */
  org.mojolang.mojo.lang.ImportDecl.Identifier getIdentifiers(int index);
  /**
   * <code>repeated .mojo.lang.ImportDecl.Identifier identifiers = 12;</code>
   */
  int getIdentifiersCount();
  /**
   * <code>repeated .mojo.lang.ImportDecl.Identifier identifiers = 12;</code>
   */
  java.util.List<? extends org.mojolang.mojo.lang.ImportDecl.IdentifierOrBuilder> 
      getIdentifiersOrBuilderList();
  /**
   * <code>repeated .mojo.lang.ImportDecl.Identifier identifiers = 12;</code>
   */
  org.mojolang.mojo.lang.ImportDecl.IdentifierOrBuilder getIdentifiersOrBuilder(
      int index);
}
