// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/type.proto

package org.mojolang.mojo.lang;

/**
 * Protobuf type {@code mojo.lang.InterfaceType}
 */
public  final class InterfaceType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.lang.InterfaceType)
    InterfaceTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use InterfaceType.newBuilder() to construct.
  private InterfaceType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private InterfaceType() {
    package_ = "";
    methods_ = java.util.Collections.emptyList();
    inherits_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private InterfaceType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (startPosition_ != null) {
              subBuilder = startPosition_.toBuilder();
            }
            startPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startPosition_);
              startPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            org.mojolang.mojo.lang.Position.Builder subBuilder = null;
            if (endPosition_ != null) {
              subBuilder = endPosition_.toBuilder();
            }
            endPosition_ = input.readMessage(org.mojolang.mojo.lang.Position.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endPosition_);
              endPosition_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            package_ = s;
            break;
          }
          case 82: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              methods_ = new java.util.ArrayList<org.mojolang.mojo.lang.FuncDecl>();
              mutable_bitField0_ |= 0x00000008;
            }
            methods_.add(
                input.readMessage(org.mojolang.mojo.lang.FuncDecl.parser(), extensionRegistry));
            break;
          }
          case 90: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              inherits_ = new java.util.ArrayList<org.mojolang.mojo.lang.NominalType>();
              mutable_bitField0_ |= 0x00000010;
            }
            inherits_.add(
                input.readMessage(org.mojolang.mojo.lang.NominalType.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        methods_ = java.util.Collections.unmodifiableList(methods_);
      }
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        inherits_ = java.util.Collections.unmodifiableList(inherits_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.lang.TypeProto.internal_static_mojo_lang_InterfaceType_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.lang.TypeProto.internal_static_mojo_lang_InterfaceType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.lang.InterfaceType.class, org.mojolang.mojo.lang.InterfaceType.Builder.class);
  }

  private int bitField0_;
  public static final int START_POSITION_FIELD_NUMBER = 1;
  private org.mojolang.mojo.lang.Position startPosition_;
  /**
   * <pre>
   *&#47; position of first character belonging to the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  public boolean hasStartPosition() {
    return startPosition_ != null;
  }
  /**
   * <pre>
   *&#47; position of first character belonging to the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  public org.mojolang.mojo.lang.Position getStartPosition() {
    return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
  }
  /**
   * <pre>
   *&#47; position of first character belonging to the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position start_position = 1;</code>
   */
  public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
    return getStartPosition();
  }

  public static final int END_POSITION_FIELD_NUMBER = 2;
  private org.mojolang.mojo.lang.Position endPosition_;
  /**
   * <pre>
   *&#47; position of first character immediately after the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  public boolean hasEndPosition() {
    return endPosition_ != null;
  }
  /**
   * <pre>
   *&#47; position of first character immediately after the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  public org.mojolang.mojo.lang.Position getEndPosition() {
    return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
  }
  /**
   * <pre>
   *&#47; position of first character immediately after the Expr
   * </pre>
   *
   * <code>.mojo.lang.Position end_position = 2;</code>
   */
  public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
    return getEndPosition();
  }

  public static final int PACKAGE_FIELD_NUMBER = 6;
  private volatile java.lang.Object package_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string package = 6;</code>
   */
  public java.lang.String getPackage() {
    java.lang.Object ref = package_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      package_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string package = 6;</code>
   */
  public com.google.protobuf.ByteString
      getPackageBytes() {
    java.lang.Object ref = package_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      package_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHODS_FIELD_NUMBER = 10;
  private java.util.List<org.mojolang.mojo.lang.FuncDecl> methods_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
   */
  public java.util.List<org.mojolang.mojo.lang.FuncDecl> getMethodsList() {
    return methods_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
   */
  public java.util.List<? extends org.mojolang.mojo.lang.FuncDeclOrBuilder> 
      getMethodsOrBuilderList() {
    return methods_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
   */
  public int getMethodsCount() {
    return methods_.size();
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
   */
  public org.mojolang.mojo.lang.FuncDecl getMethods(int index) {
    return methods_.get(index);
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
   */
  public org.mojolang.mojo.lang.FuncDeclOrBuilder getMethodsOrBuilder(
      int index) {
    return methods_.get(index);
  }

  public static final int INHERITS_FIELD_NUMBER = 11;
  private java.util.List<org.mojolang.mojo.lang.NominalType> inherits_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
   */
  public java.util.List<org.mojolang.mojo.lang.NominalType> getInheritsList() {
    return inherits_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
   */
  public java.util.List<? extends org.mojolang.mojo.lang.NominalTypeOrBuilder> 
      getInheritsOrBuilderList() {
    return inherits_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
   */
  public int getInheritsCount() {
    return inherits_.size();
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
   */
  public org.mojolang.mojo.lang.NominalType getInherits(int index) {
    return inherits_.get(index);
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
   */
  public org.mojolang.mojo.lang.NominalTypeOrBuilder getInheritsOrBuilder(
      int index) {
    return inherits_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startPosition_ != null) {
      output.writeMessage(1, getStartPosition());
    }
    if (endPosition_ != null) {
      output.writeMessage(2, getEndPosition());
    }
    if (!getPackageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, package_);
    }
    for (int i = 0; i < methods_.size(); i++) {
      output.writeMessage(10, methods_.get(i));
    }
    for (int i = 0; i < inherits_.size(); i++) {
      output.writeMessage(11, inherits_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartPosition());
    }
    if (endPosition_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndPosition());
    }
    if (!getPackageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, package_);
    }
    for (int i = 0; i < methods_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, methods_.get(i));
    }
    for (int i = 0; i < inherits_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, inherits_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.lang.InterfaceType)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.lang.InterfaceType other = (org.mojolang.mojo.lang.InterfaceType) obj;

    boolean result = true;
    result = result && (hasStartPosition() == other.hasStartPosition());
    if (hasStartPosition()) {
      result = result && getStartPosition()
          .equals(other.getStartPosition());
    }
    result = result && (hasEndPosition() == other.hasEndPosition());
    if (hasEndPosition()) {
      result = result && getEndPosition()
          .equals(other.getEndPosition());
    }
    result = result && getPackage()
        .equals(other.getPackage());
    result = result && getMethodsList()
        .equals(other.getMethodsList());
    result = result && getInheritsList()
        .equals(other.getInheritsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartPosition()) {
      hash = (37 * hash) + START_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getStartPosition().hashCode();
    }
    if (hasEndPosition()) {
      hash = (37 * hash) + END_POSITION_FIELD_NUMBER;
      hash = (53 * hash) + getEndPosition().hashCode();
    }
    hash = (37 * hash) + PACKAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPackage().hashCode();
    if (getMethodsCount() > 0) {
      hash = (37 * hash) + METHODS_FIELD_NUMBER;
      hash = (53 * hash) + getMethodsList().hashCode();
    }
    if (getInheritsCount() > 0) {
      hash = (37 * hash) + INHERITS_FIELD_NUMBER;
      hash = (53 * hash) + getInheritsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.lang.InterfaceType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.InterfaceType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.lang.InterfaceType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.lang.InterfaceType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.lang.InterfaceType)
      org.mojolang.mojo.lang.InterfaceTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.lang.TypeProto.internal_static_mojo_lang_InterfaceType_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.lang.TypeProto.internal_static_mojo_lang_InterfaceType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.lang.InterfaceType.class, org.mojolang.mojo.lang.InterfaceType.Builder.class);
    }

    // Construct using org.mojolang.mojo.lang.InterfaceType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMethodsFieldBuilder();
        getInheritsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }
      package_ = "";

      if (methodsBuilder_ == null) {
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        methodsBuilder_.clear();
      }
      if (inheritsBuilder_ == null) {
        inherits_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        inheritsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.lang.TypeProto.internal_static_mojo_lang_InterfaceType_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.InterfaceType getDefaultInstanceForType() {
      return org.mojolang.mojo.lang.InterfaceType.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.InterfaceType build() {
      org.mojolang.mojo.lang.InterfaceType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.InterfaceType buildPartial() {
      org.mojolang.mojo.lang.InterfaceType result = new org.mojolang.mojo.lang.InterfaceType(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (startPositionBuilder_ == null) {
        result.startPosition_ = startPosition_;
      } else {
        result.startPosition_ = startPositionBuilder_.build();
      }
      if (endPositionBuilder_ == null) {
        result.endPosition_ = endPosition_;
      } else {
        result.endPosition_ = endPositionBuilder_.build();
      }
      result.package_ = package_;
      if (methodsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          methods_ = java.util.Collections.unmodifiableList(methods_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.methods_ = methods_;
      } else {
        result.methods_ = methodsBuilder_.build();
      }
      if (inheritsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          inherits_ = java.util.Collections.unmodifiableList(inherits_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.inherits_ = inherits_;
      } else {
        result.inherits_ = inheritsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.lang.InterfaceType) {
        return mergeFrom((org.mojolang.mojo.lang.InterfaceType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.lang.InterfaceType other) {
      if (other == org.mojolang.mojo.lang.InterfaceType.getDefaultInstance()) return this;
      if (other.hasStartPosition()) {
        mergeStartPosition(other.getStartPosition());
      }
      if (other.hasEndPosition()) {
        mergeEndPosition(other.getEndPosition());
      }
      if (!other.getPackage().isEmpty()) {
        package_ = other.package_;
        onChanged();
      }
      if (methodsBuilder_ == null) {
        if (!other.methods_.isEmpty()) {
          if (methods_.isEmpty()) {
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureMethodsIsMutable();
            methods_.addAll(other.methods_);
          }
          onChanged();
        }
      } else {
        if (!other.methods_.isEmpty()) {
          if (methodsBuilder_.isEmpty()) {
            methodsBuilder_.dispose();
            methodsBuilder_ = null;
            methods_ = other.methods_;
            bitField0_ = (bitField0_ & ~0x00000008);
            methodsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMethodsFieldBuilder() : null;
          } else {
            methodsBuilder_.addAllMessages(other.methods_);
          }
        }
      }
      if (inheritsBuilder_ == null) {
        if (!other.inherits_.isEmpty()) {
          if (inherits_.isEmpty()) {
            inherits_ = other.inherits_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureInheritsIsMutable();
            inherits_.addAll(other.inherits_);
          }
          onChanged();
        }
      } else {
        if (!other.inherits_.isEmpty()) {
          if (inheritsBuilder_.isEmpty()) {
            inheritsBuilder_.dispose();
            inheritsBuilder_ = null;
            inherits_ = other.inherits_;
            bitField0_ = (bitField0_ & ~0x00000010);
            inheritsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInheritsFieldBuilder() : null;
          } else {
            inheritsBuilder_.addAllMessages(other.inherits_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.lang.InterfaceType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.lang.InterfaceType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private org.mojolang.mojo.lang.Position startPosition_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> startPositionBuilder_;
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public boolean hasStartPosition() {
      return startPositionBuilder_ != null || startPosition_ != null;
    }
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.Position getStartPosition() {
      if (startPositionBuilder_ == null) {
        return startPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      } else {
        return startPositionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startPosition_ = value;
        onChanged();
      } else {
        startPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder setStartPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (startPositionBuilder_ == null) {
        startPosition_ = builderForValue.build();
        onChanged();
      } else {
        startPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder mergeStartPosition(org.mojolang.mojo.lang.Position value) {
      if (startPositionBuilder_ == null) {
        if (startPosition_ != null) {
          startPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(startPosition_).mergeFrom(value).buildPartial();
        } else {
          startPosition_ = value;
        }
        onChanged();
      } else {
        startPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public Builder clearStartPosition() {
      if (startPositionBuilder_ == null) {
        startPosition_ = null;
        onChanged();
      } else {
        startPosition_ = null;
        startPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getStartPositionBuilder() {
      
      onChanged();
      return getStartPositionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getStartPositionOrBuilder() {
      if (startPositionBuilder_ != null) {
        return startPositionBuilder_.getMessageOrBuilder();
      } else {
        return startPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : startPosition_;
      }
    }
    /**
     * <pre>
     *&#47; position of first character belonging to the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position start_position = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getStartPositionFieldBuilder() {
      if (startPositionBuilder_ == null) {
        startPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getStartPosition(),
                getParentForChildren(),
                isClean());
        startPosition_ = null;
      }
      return startPositionBuilder_;
    }

    private org.mojolang.mojo.lang.Position endPosition_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> endPositionBuilder_;
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public boolean hasEndPosition() {
      return endPositionBuilder_ != null || endPosition_ != null;
    }
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.Position getEndPosition() {
      if (endPositionBuilder_ == null) {
        return endPosition_ == null ? org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      } else {
        return endPositionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endPosition_ = value;
        onChanged();
      } else {
        endPositionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder setEndPosition(
        org.mojolang.mojo.lang.Position.Builder builderForValue) {
      if (endPositionBuilder_ == null) {
        endPosition_ = builderForValue.build();
        onChanged();
      } else {
        endPositionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder mergeEndPosition(org.mojolang.mojo.lang.Position value) {
      if (endPositionBuilder_ == null) {
        if (endPosition_ != null) {
          endPosition_ =
            org.mojolang.mojo.lang.Position.newBuilder(endPosition_).mergeFrom(value).buildPartial();
        } else {
          endPosition_ = value;
        }
        onChanged();
      } else {
        endPositionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public Builder clearEndPosition() {
      if (endPositionBuilder_ == null) {
        endPosition_ = null;
        onChanged();
      } else {
        endPosition_ = null;
        endPositionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.Position.Builder getEndPositionBuilder() {
      
      onChanged();
      return getEndPositionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    public org.mojolang.mojo.lang.PositionOrBuilder getEndPositionOrBuilder() {
      if (endPositionBuilder_ != null) {
        return endPositionBuilder_.getMessageOrBuilder();
      } else {
        return endPosition_ == null ?
            org.mojolang.mojo.lang.Position.getDefaultInstance() : endPosition_;
      }
    }
    /**
     * <pre>
     *&#47; position of first character immediately after the Expr
     * </pre>
     *
     * <code>.mojo.lang.Position end_position = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder> 
        getEndPositionFieldBuilder() {
      if (endPositionBuilder_ == null) {
        endPositionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Position, org.mojolang.mojo.lang.Position.Builder, org.mojolang.mojo.lang.PositionOrBuilder>(
                getEndPosition(),
                getParentForChildren(),
                isClean());
        endPosition_ = null;
      }
      return endPositionBuilder_;
    }

    private java.lang.Object package_ = "";
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string package = 6;</code>
     */
    public java.lang.String getPackage() {
      java.lang.Object ref = package_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        package_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string package = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPackageBytes() {
      java.lang.Object ref = package_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        package_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string package = 6;</code>
     */
    public Builder setPackage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      package_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string package = 6;</code>
     */
    public Builder clearPackage() {
      
      package_ = getDefaultInstance().getPackage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string package = 6;</code>
     */
    public Builder setPackageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      package_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.mojolang.mojo.lang.FuncDecl> methods_ =
      java.util.Collections.emptyList();
    private void ensureMethodsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        methods_ = new java.util.ArrayList<org.mojolang.mojo.lang.FuncDecl>(methods_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.FuncDecl, org.mojolang.mojo.lang.FuncDecl.Builder, org.mojolang.mojo.lang.FuncDeclOrBuilder> methodsBuilder_;

    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.FuncDecl> getMethodsList() {
      if (methodsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(methods_);
      } else {
        return methodsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public int getMethodsCount() {
      if (methodsBuilder_ == null) {
        return methods_.size();
      } else {
        return methodsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public org.mojolang.mojo.lang.FuncDecl getMethods(int index) {
      if (methodsBuilder_ == null) {
        return methods_.get(index);
      } else {
        return methodsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder setMethods(
        int index, org.mojolang.mojo.lang.FuncDecl value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.set(index, value);
        onChanged();
      } else {
        methodsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder setMethods(
        int index, org.mojolang.mojo.lang.FuncDecl.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.set(index, builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder addMethods(org.mojolang.mojo.lang.FuncDecl value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(value);
        onChanged();
      } else {
        methodsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder addMethods(
        int index, org.mojolang.mojo.lang.FuncDecl value) {
      if (methodsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMethodsIsMutable();
        methods_.add(index, value);
        onChanged();
      } else {
        methodsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder addMethods(
        org.mojolang.mojo.lang.FuncDecl.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.add(builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder addMethods(
        int index, org.mojolang.mojo.lang.FuncDecl.Builder builderForValue) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.add(index, builderForValue.build());
        onChanged();
      } else {
        methodsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder addAllMethods(
        java.lang.Iterable<? extends org.mojolang.mojo.lang.FuncDecl> values) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, methods_);
        onChanged();
      } else {
        methodsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder clearMethods() {
      if (methodsBuilder_ == null) {
        methods_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        methodsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public Builder removeMethods(int index) {
      if (methodsBuilder_ == null) {
        ensureMethodsIsMutable();
        methods_.remove(index);
        onChanged();
      } else {
        methodsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public org.mojolang.mojo.lang.FuncDecl.Builder getMethodsBuilder(
        int index) {
      return getMethodsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public org.mojolang.mojo.lang.FuncDeclOrBuilder getMethodsOrBuilder(
        int index) {
      if (methodsBuilder_ == null) {
        return methods_.get(index);  } else {
        return methodsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.lang.FuncDeclOrBuilder> 
         getMethodsOrBuilderList() {
      if (methodsBuilder_ != null) {
        return methodsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(methods_);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public org.mojolang.mojo.lang.FuncDecl.Builder addMethodsBuilder() {
      return getMethodsFieldBuilder().addBuilder(
          org.mojolang.mojo.lang.FuncDecl.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public org.mojolang.mojo.lang.FuncDecl.Builder addMethodsBuilder(
        int index) {
      return getMethodsFieldBuilder().addBuilder(
          index, org.mojolang.mojo.lang.FuncDecl.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.FuncDecl methods = 10;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.FuncDecl.Builder> 
         getMethodsBuilderList() {
      return getMethodsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.FuncDecl, org.mojolang.mojo.lang.FuncDecl.Builder, org.mojolang.mojo.lang.FuncDeclOrBuilder> 
        getMethodsFieldBuilder() {
      if (methodsBuilder_ == null) {
        methodsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.lang.FuncDecl, org.mojolang.mojo.lang.FuncDecl.Builder, org.mojolang.mojo.lang.FuncDeclOrBuilder>(
                methods_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        methods_ = null;
      }
      return methodsBuilder_;
    }

    private java.util.List<org.mojolang.mojo.lang.NominalType> inherits_ =
      java.util.Collections.emptyList();
    private void ensureInheritsIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        inherits_ = new java.util.ArrayList<org.mojolang.mojo.lang.NominalType>(inherits_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.NominalType, org.mojolang.mojo.lang.NominalType.Builder, org.mojolang.mojo.lang.NominalTypeOrBuilder> inheritsBuilder_;

    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.NominalType> getInheritsList() {
      if (inheritsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(inherits_);
      } else {
        return inheritsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public int getInheritsCount() {
      if (inheritsBuilder_ == null) {
        return inherits_.size();
      } else {
        return inheritsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public org.mojolang.mojo.lang.NominalType getInherits(int index) {
      if (inheritsBuilder_ == null) {
        return inherits_.get(index);
      } else {
        return inheritsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder setInherits(
        int index, org.mojolang.mojo.lang.NominalType value) {
      if (inheritsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInheritsIsMutable();
        inherits_.set(index, value);
        onChanged();
      } else {
        inheritsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder setInherits(
        int index, org.mojolang.mojo.lang.NominalType.Builder builderForValue) {
      if (inheritsBuilder_ == null) {
        ensureInheritsIsMutable();
        inherits_.set(index, builderForValue.build());
        onChanged();
      } else {
        inheritsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder addInherits(org.mojolang.mojo.lang.NominalType value) {
      if (inheritsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInheritsIsMutable();
        inherits_.add(value);
        onChanged();
      } else {
        inheritsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder addInherits(
        int index, org.mojolang.mojo.lang.NominalType value) {
      if (inheritsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInheritsIsMutable();
        inherits_.add(index, value);
        onChanged();
      } else {
        inheritsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder addInherits(
        org.mojolang.mojo.lang.NominalType.Builder builderForValue) {
      if (inheritsBuilder_ == null) {
        ensureInheritsIsMutable();
        inherits_.add(builderForValue.build());
        onChanged();
      } else {
        inheritsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder addInherits(
        int index, org.mojolang.mojo.lang.NominalType.Builder builderForValue) {
      if (inheritsBuilder_ == null) {
        ensureInheritsIsMutable();
        inherits_.add(index, builderForValue.build());
        onChanged();
      } else {
        inheritsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder addAllInherits(
        java.lang.Iterable<? extends org.mojolang.mojo.lang.NominalType> values) {
      if (inheritsBuilder_ == null) {
        ensureInheritsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, inherits_);
        onChanged();
      } else {
        inheritsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder clearInherits() {
      if (inheritsBuilder_ == null) {
        inherits_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        inheritsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public Builder removeInherits(int index) {
      if (inheritsBuilder_ == null) {
        ensureInheritsIsMutable();
        inherits_.remove(index);
        onChanged();
      } else {
        inheritsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public org.mojolang.mojo.lang.NominalType.Builder getInheritsBuilder(
        int index) {
      return getInheritsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public org.mojolang.mojo.lang.NominalTypeOrBuilder getInheritsOrBuilder(
        int index) {
      if (inheritsBuilder_ == null) {
        return inherits_.get(index);  } else {
        return inheritsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.lang.NominalTypeOrBuilder> 
         getInheritsOrBuilderList() {
      if (inheritsBuilder_ != null) {
        return inheritsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(inherits_);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public org.mojolang.mojo.lang.NominalType.Builder addInheritsBuilder() {
      return getInheritsFieldBuilder().addBuilder(
          org.mojolang.mojo.lang.NominalType.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public org.mojolang.mojo.lang.NominalType.Builder addInheritsBuilder(
        int index) {
      return getInheritsFieldBuilder().addBuilder(
          index, org.mojolang.mojo.lang.NominalType.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.NominalType inherits = 11;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.NominalType.Builder> 
         getInheritsBuilderList() {
      return getInheritsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.NominalType, org.mojolang.mojo.lang.NominalType.Builder, org.mojolang.mojo.lang.NominalTypeOrBuilder> 
        getInheritsFieldBuilder() {
      if (inheritsBuilder_ == null) {
        inheritsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.lang.NominalType, org.mojolang.mojo.lang.NominalType.Builder, org.mojolang.mojo.lang.NominalTypeOrBuilder>(
                inherits_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        inherits_ = null;
      }
      return inheritsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.lang.InterfaceType)
  }

  // @@protoc_insertion_point(class_scope:mojo.lang.InterfaceType)
  private static final org.mojolang.mojo.lang.InterfaceType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.lang.InterfaceType();
  }

  public static org.mojolang.mojo.lang.InterfaceType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InterfaceType>
      PARSER = new com.google.protobuf.AbstractParser<InterfaceType>() {
    @java.lang.Override
    public InterfaceType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new InterfaceType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<InterfaceType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InterfaceType> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.lang.InterfaceType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

