// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/lang/package.proto

package org.mojolang.mojo.lang;

/**
 * <pre>
 *&#47; A Package represents a set of source files
 * / collectively building a Mojo package.
 * </pre>
 *
 * Protobuf type {@code mojo.lang.Package}
 */
public  final class Package extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.lang.Package)
    PackageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Package.newBuilder() to construct.
  private Package(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Package() {
    name_ = "";
    fullName_ = "";
    children_ = java.util.Collections.emptyList();
    summary_ = "";
    license_ = "";
    sourceFiles_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Package(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            fullName_ = s;
            break;
          }
          case 26: {
            org.mojolang.mojo.core.Version.Builder subBuilder = null;
            if (version_ != null) {
              subBuilder = version_.toBuilder();
            }
            version_ = input.readMessage(org.mojolang.mojo.core.Version.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(version_);
              version_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            org.mojolang.mojo.lang.Package.Builder subBuilder = null;
            if (parent_ != null) {
              subBuilder = parent_.toBuilder();
            }
            parent_ = input.readMessage(org.mojolang.mojo.lang.Package.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(parent_);
              parent_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              children_ = new java.util.ArrayList<org.mojolang.mojo.lang.Package>();
              mutable_bitField0_ |= 0x00000010;
            }
            children_.add(
                input.readMessage(org.mojolang.mojo.lang.Package.parser(), extensionRegistry));
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            summary_ = s;
            break;
          }
          case 90: {
            org.mojolang.mojo.core.Url.Builder subBuilder = null;
            if (repository_ != null) {
              subBuilder = repository_.toBuilder();
            }
            repository_ = input.readMessage(org.mojolang.mojo.core.Url.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(repository_);
              repository_ = subBuilder.buildPartial();
            }

            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            license_ = s;
            break;
          }
          case 138: {
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              sourceFiles_ = new java.util.ArrayList<org.mojolang.mojo.lang.SourceFile>();
              mutable_bitField0_ |= 0x00000100;
            }
            sourceFiles_.add(
                input.readMessage(org.mojolang.mojo.lang.SourceFile.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        children_ = java.util.Collections.unmodifiableList(children_);
      }
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        sourceFiles_ = java.util.Collections.unmodifiableList(sourceFiles_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.lang.PackageProto.internal_static_mojo_lang_Package_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.lang.PackageProto.internal_static_mojo_lang_Package_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.lang.Package.class, org.mojolang.mojo.lang.Package.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *&#47; package name
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47; package name
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FULL_NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object fullName_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string full_name = 2;</code>
   */
  public java.lang.String getFullName() {
    java.lang.Object ref = fullName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fullName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string full_name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getFullNameBytes() {
    java.lang.Object ref = fullName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fullName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 3;
  private org.mojolang.mojo.core.Version version_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.core.Version version = 3;</code>
   */
  public boolean hasVersion() {
    return version_ != null;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.core.Version version = 3;</code>
   */
  public org.mojolang.mojo.core.Version getVersion() {
    return version_ == null ? org.mojolang.mojo.core.Version.getDefaultInstance() : version_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.core.Version version = 3;</code>
   */
  public org.mojolang.mojo.core.VersionOrBuilder getVersionOrBuilder() {
    return getVersion();
  }

  public static final int PARENT_FIELD_NUMBER = 4;
  private org.mojolang.mojo.lang.Package parent_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.lang.Package parent = 4;</code>
   */
  public boolean hasParent() {
    return parent_ != null;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.lang.Package parent = 4;</code>
   */
  public org.mojolang.mojo.lang.Package getParent() {
    return parent_ == null ? org.mojolang.mojo.lang.Package.getDefaultInstance() : parent_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.lang.Package parent = 4;</code>
   */
  public org.mojolang.mojo.lang.PackageOrBuilder getParentOrBuilder() {
    return getParent();
  }

  public static final int CHILDREN_FIELD_NUMBER = 5;
  private java.util.List<org.mojolang.mojo.lang.Package> children_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.Package children = 5;</code>
   */
  public java.util.List<org.mojolang.mojo.lang.Package> getChildrenList() {
    return children_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.Package children = 5;</code>
   */
  public java.util.List<? extends org.mojolang.mojo.lang.PackageOrBuilder> 
      getChildrenOrBuilderList() {
    return children_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.Package children = 5;</code>
   */
  public int getChildrenCount() {
    return children_.size();
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.Package children = 5;</code>
   */
  public org.mojolang.mojo.lang.Package getChildren(int index) {
    return children_.get(index);
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.Package children = 5;</code>
   */
  public org.mojolang.mojo.lang.PackageOrBuilder getChildrenOrBuilder(
      int index) {
    return children_.get(index);
  }

  public static final int SUMMARY_FIELD_NUMBER = 10;
  private volatile java.lang.Object summary_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string summary = 10;</code>
   */
  public java.lang.String getSummary() {
    java.lang.Object ref = summary_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      summary_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string summary = 10;</code>
   */
  public com.google.protobuf.ByteString
      getSummaryBytes() {
    java.lang.Object ref = summary_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      summary_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPOSITORY_FIELD_NUMBER = 11;
  private org.mojolang.mojo.core.Url repository_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.core.Url repository = 11;</code>
   */
  public boolean hasRepository() {
    return repository_ != null;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.core.Url repository = 11;</code>
   */
  public org.mojolang.mojo.core.Url getRepository() {
    return repository_ == null ? org.mojolang.mojo.core.Url.getDefaultInstance() : repository_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>.mojo.core.Url repository = 11;</code>
   */
  public org.mojolang.mojo.core.UrlOrBuilder getRepositoryOrBuilder() {
    return getRepository();
  }

  public static final int LICENSE_FIELD_NUMBER = 12;
  private volatile java.lang.Object license_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string license = 12;</code>
   */
  public java.lang.String getLicense() {
    java.lang.Object ref = license_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      license_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>string license = 12;</code>
   */
  public com.google.protobuf.ByteString
      getLicenseBytes() {
    java.lang.Object ref = license_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      license_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCE_FILES_FIELD_NUMBER = 17;
  private java.util.List<org.mojolang.mojo.lang.SourceFile> sourceFiles_;
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
   */
  public java.util.List<org.mojolang.mojo.lang.SourceFile> getSourceFilesList() {
    return sourceFiles_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
   */
  public java.util.List<? extends org.mojolang.mojo.lang.SourceFileOrBuilder> 
      getSourceFilesOrBuilderList() {
    return sourceFiles_;
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
   */
  public int getSourceFilesCount() {
    return sourceFiles_.size();
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
   */
  public org.mojolang.mojo.lang.SourceFile getSourceFiles(int index) {
    return sourceFiles_.get(index);
  }
  /**
   * <pre>
   *&#47;
   * </pre>
   *
   * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
   */
  public org.mojolang.mojo.lang.SourceFileOrBuilder getSourceFilesOrBuilder(
      int index) {
    return sourceFiles_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getFullNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, fullName_);
    }
    if (version_ != null) {
      output.writeMessage(3, getVersion());
    }
    if (parent_ != null) {
      output.writeMessage(4, getParent());
    }
    for (int i = 0; i < children_.size(); i++) {
      output.writeMessage(5, children_.get(i));
    }
    if (!getSummaryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, summary_);
    }
    if (repository_ != null) {
      output.writeMessage(11, getRepository());
    }
    if (!getLicenseBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, license_);
    }
    for (int i = 0; i < sourceFiles_.size(); i++) {
      output.writeMessage(17, sourceFiles_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getFullNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, fullName_);
    }
    if (version_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getVersion());
    }
    if (parent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getParent());
    }
    for (int i = 0; i < children_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, children_.get(i));
    }
    if (!getSummaryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, summary_);
    }
    if (repository_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(11, getRepository());
    }
    if (!getLicenseBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, license_);
    }
    for (int i = 0; i < sourceFiles_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(17, sourceFiles_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.lang.Package)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.lang.Package other = (org.mojolang.mojo.lang.Package) obj;

    boolean result = true;
    result = result && getName()
        .equals(other.getName());
    result = result && getFullName()
        .equals(other.getFullName());
    result = result && (hasVersion() == other.hasVersion());
    if (hasVersion()) {
      result = result && getVersion()
          .equals(other.getVersion());
    }
    result = result && (hasParent() == other.hasParent());
    if (hasParent()) {
      result = result && getParent()
          .equals(other.getParent());
    }
    result = result && getChildrenList()
        .equals(other.getChildrenList());
    result = result && getSummary()
        .equals(other.getSummary());
    result = result && (hasRepository() == other.hasRepository());
    if (hasRepository()) {
      result = result && getRepository()
          .equals(other.getRepository());
    }
    result = result && getLicense()
        .equals(other.getLicense());
    result = result && getSourceFilesList()
        .equals(other.getSourceFilesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + FULL_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFullName().hashCode();
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    if (hasParent()) {
      hash = (37 * hash) + PARENT_FIELD_NUMBER;
      hash = (53 * hash) + getParent().hashCode();
    }
    if (getChildrenCount() > 0) {
      hash = (37 * hash) + CHILDREN_FIELD_NUMBER;
      hash = (53 * hash) + getChildrenList().hashCode();
    }
    hash = (37 * hash) + SUMMARY_FIELD_NUMBER;
    hash = (53 * hash) + getSummary().hashCode();
    if (hasRepository()) {
      hash = (37 * hash) + REPOSITORY_FIELD_NUMBER;
      hash = (53 * hash) + getRepository().hashCode();
    }
    hash = (37 * hash) + LICENSE_FIELD_NUMBER;
    hash = (53 * hash) + getLicense().hashCode();
    if (getSourceFilesCount() > 0) {
      hash = (37 * hash) + SOURCE_FILES_FIELD_NUMBER;
      hash = (53 * hash) + getSourceFilesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.lang.Package parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.Package parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.Package parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.lang.Package parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.lang.Package prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *&#47; A Package represents a set of source files
   * / collectively building a Mojo package.
   * </pre>
   *
   * Protobuf type {@code mojo.lang.Package}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.lang.Package)
      org.mojolang.mojo.lang.PackageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.lang.PackageProto.internal_static_mojo_lang_Package_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.lang.PackageProto.internal_static_mojo_lang_Package_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.lang.Package.class, org.mojolang.mojo.lang.Package.Builder.class);
    }

    // Construct using org.mojolang.mojo.lang.Package.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getChildrenFieldBuilder();
        getSourceFilesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      fullName_ = "";

      if (versionBuilder_ == null) {
        version_ = null;
      } else {
        version_ = null;
        versionBuilder_ = null;
      }
      if (parentBuilder_ == null) {
        parent_ = null;
      } else {
        parent_ = null;
        parentBuilder_ = null;
      }
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
      } else {
        childrenBuilder_.clear();
      }
      summary_ = "";

      if (repositoryBuilder_ == null) {
        repository_ = null;
      } else {
        repository_ = null;
        repositoryBuilder_ = null;
      }
      license_ = "";

      if (sourceFilesBuilder_ == null) {
        sourceFiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
      } else {
        sourceFilesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.lang.PackageProto.internal_static_mojo_lang_Package_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.Package getDefaultInstanceForType() {
      return org.mojolang.mojo.lang.Package.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.Package build() {
      org.mojolang.mojo.lang.Package result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.lang.Package buildPartial() {
      org.mojolang.mojo.lang.Package result = new org.mojolang.mojo.lang.Package(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.name_ = name_;
      result.fullName_ = fullName_;
      if (versionBuilder_ == null) {
        result.version_ = version_;
      } else {
        result.version_ = versionBuilder_.build();
      }
      if (parentBuilder_ == null) {
        result.parent_ = parent_;
      } else {
        result.parent_ = parentBuilder_.build();
      }
      if (childrenBuilder_ == null) {
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          children_ = java.util.Collections.unmodifiableList(children_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.children_ = children_;
      } else {
        result.children_ = childrenBuilder_.build();
      }
      result.summary_ = summary_;
      if (repositoryBuilder_ == null) {
        result.repository_ = repository_;
      } else {
        result.repository_ = repositoryBuilder_.build();
      }
      result.license_ = license_;
      if (sourceFilesBuilder_ == null) {
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          sourceFiles_ = java.util.Collections.unmodifiableList(sourceFiles_);
          bitField0_ = (bitField0_ & ~0x00000100);
        }
        result.sourceFiles_ = sourceFiles_;
      } else {
        result.sourceFiles_ = sourceFilesBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.lang.Package) {
        return mergeFrom((org.mojolang.mojo.lang.Package)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.lang.Package other) {
      if (other == org.mojolang.mojo.lang.Package.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getFullName().isEmpty()) {
        fullName_ = other.fullName_;
        onChanged();
      }
      if (other.hasVersion()) {
        mergeVersion(other.getVersion());
      }
      if (other.hasParent()) {
        mergeParent(other.getParent());
      }
      if (childrenBuilder_ == null) {
        if (!other.children_.isEmpty()) {
          if (children_.isEmpty()) {
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureChildrenIsMutable();
            children_.addAll(other.children_);
          }
          onChanged();
        }
      } else {
        if (!other.children_.isEmpty()) {
          if (childrenBuilder_.isEmpty()) {
            childrenBuilder_.dispose();
            childrenBuilder_ = null;
            children_ = other.children_;
            bitField0_ = (bitField0_ & ~0x00000010);
            childrenBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getChildrenFieldBuilder() : null;
          } else {
            childrenBuilder_.addAllMessages(other.children_);
          }
        }
      }
      if (!other.getSummary().isEmpty()) {
        summary_ = other.summary_;
        onChanged();
      }
      if (other.hasRepository()) {
        mergeRepository(other.getRepository());
      }
      if (!other.getLicense().isEmpty()) {
        license_ = other.license_;
        onChanged();
      }
      if (sourceFilesBuilder_ == null) {
        if (!other.sourceFiles_.isEmpty()) {
          if (sourceFiles_.isEmpty()) {
            sourceFiles_ = other.sourceFiles_;
            bitField0_ = (bitField0_ & ~0x00000100);
          } else {
            ensureSourceFilesIsMutable();
            sourceFiles_.addAll(other.sourceFiles_);
          }
          onChanged();
        }
      } else {
        if (!other.sourceFiles_.isEmpty()) {
          if (sourceFilesBuilder_.isEmpty()) {
            sourceFilesBuilder_.dispose();
            sourceFilesBuilder_ = null;
            sourceFiles_ = other.sourceFiles_;
            bitField0_ = (bitField0_ & ~0x00000100);
            sourceFilesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSourceFilesFieldBuilder() : null;
          } else {
            sourceFilesBuilder_.addAllMessages(other.sourceFiles_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.mojolang.mojo.lang.Package parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.mojolang.mojo.lang.Package) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *&#47; package name
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47; package name
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47; package name
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; package name
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47; package name
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fullName_ = "";
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string full_name = 2;</code>
     */
    public java.lang.String getFullName() {
      java.lang.Object ref = fullName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fullName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string full_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFullNameBytes() {
      java.lang.Object ref = fullName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fullName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string full_name = 2;</code>
     */
    public Builder setFullName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fullName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string full_name = 2;</code>
     */
    public Builder clearFullName() {
      
      fullName_ = getDefaultInstance().getFullName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string full_name = 2;</code>
     */
    public Builder setFullNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fullName_ = value;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.core.Version version_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Version, org.mojolang.mojo.core.Version.Builder, org.mojolang.mojo.core.VersionOrBuilder> versionBuilder_;
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    public boolean hasVersion() {
      return versionBuilder_ != null || version_ != null;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    public org.mojolang.mojo.core.Version getVersion() {
      if (versionBuilder_ == null) {
        return version_ == null ? org.mojolang.mojo.core.Version.getDefaultInstance() : version_;
      } else {
        return versionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    public Builder setVersion(org.mojolang.mojo.core.Version value) {
      if (versionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;
        onChanged();
      } else {
        versionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    public Builder setVersion(
        org.mojolang.mojo.core.Version.Builder builderForValue) {
      if (versionBuilder_ == null) {
        version_ = builderForValue.build();
        onChanged();
      } else {
        versionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    public Builder mergeVersion(org.mojolang.mojo.core.Version value) {
      if (versionBuilder_ == null) {
        if (version_ != null) {
          version_ =
            org.mojolang.mojo.core.Version.newBuilder(version_).mergeFrom(value).buildPartial();
        } else {
          version_ = value;
        }
        onChanged();
      } else {
        versionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    public Builder clearVersion() {
      if (versionBuilder_ == null) {
        version_ = null;
        onChanged();
      } else {
        version_ = null;
        versionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    public org.mojolang.mojo.core.Version.Builder getVersionBuilder() {
      
      onChanged();
      return getVersionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    public org.mojolang.mojo.core.VersionOrBuilder getVersionOrBuilder() {
      if (versionBuilder_ != null) {
        return versionBuilder_.getMessageOrBuilder();
      } else {
        return version_ == null ?
            org.mojolang.mojo.core.Version.getDefaultInstance() : version_;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Version version = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Version, org.mojolang.mojo.core.Version.Builder, org.mojolang.mojo.core.VersionOrBuilder> 
        getVersionFieldBuilder() {
      if (versionBuilder_ == null) {
        versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Version, org.mojolang.mojo.core.Version.Builder, org.mojolang.mojo.core.VersionOrBuilder>(
                getVersion(),
                getParentForChildren(),
                isClean());
        version_ = null;
      }
      return versionBuilder_;
    }

    private org.mojolang.mojo.lang.Package parent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Package, org.mojolang.mojo.lang.Package.Builder, org.mojolang.mojo.lang.PackageOrBuilder> parentBuilder_;
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    public boolean hasParent() {
      return parentBuilder_ != null || parent_ != null;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    public org.mojolang.mojo.lang.Package getParent() {
      if (parentBuilder_ == null) {
        return parent_ == null ? org.mojolang.mojo.lang.Package.getDefaultInstance() : parent_;
      } else {
        return parentBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    public Builder setParent(org.mojolang.mojo.lang.Package value) {
      if (parentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        parent_ = value;
        onChanged();
      } else {
        parentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    public Builder setParent(
        org.mojolang.mojo.lang.Package.Builder builderForValue) {
      if (parentBuilder_ == null) {
        parent_ = builderForValue.build();
        onChanged();
      } else {
        parentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    public Builder mergeParent(org.mojolang.mojo.lang.Package value) {
      if (parentBuilder_ == null) {
        if (parent_ != null) {
          parent_ =
            org.mojolang.mojo.lang.Package.newBuilder(parent_).mergeFrom(value).buildPartial();
        } else {
          parent_ = value;
        }
        onChanged();
      } else {
        parentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    public Builder clearParent() {
      if (parentBuilder_ == null) {
        parent_ = null;
        onChanged();
      } else {
        parent_ = null;
        parentBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    public org.mojolang.mojo.lang.Package.Builder getParentBuilder() {
      
      onChanged();
      return getParentFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    public org.mojolang.mojo.lang.PackageOrBuilder getParentOrBuilder() {
      if (parentBuilder_ != null) {
        return parentBuilder_.getMessageOrBuilder();
      } else {
        return parent_ == null ?
            org.mojolang.mojo.lang.Package.getDefaultInstance() : parent_;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.lang.Package parent = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.lang.Package, org.mojolang.mojo.lang.Package.Builder, org.mojolang.mojo.lang.PackageOrBuilder> 
        getParentFieldBuilder() {
      if (parentBuilder_ == null) {
        parentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.lang.Package, org.mojolang.mojo.lang.Package.Builder, org.mojolang.mojo.lang.PackageOrBuilder>(
                getParent(),
                getParentForChildren(),
                isClean());
        parent_ = null;
      }
      return parentBuilder_;
    }

    private java.util.List<org.mojolang.mojo.lang.Package> children_ =
      java.util.Collections.emptyList();
    private void ensureChildrenIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        children_ = new java.util.ArrayList<org.mojolang.mojo.lang.Package>(children_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.Package, org.mojolang.mojo.lang.Package.Builder, org.mojolang.mojo.lang.PackageOrBuilder> childrenBuilder_;

    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.Package> getChildrenList() {
      if (childrenBuilder_ == null) {
        return java.util.Collections.unmodifiableList(children_);
      } else {
        return childrenBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public int getChildrenCount() {
      if (childrenBuilder_ == null) {
        return children_.size();
      } else {
        return childrenBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public org.mojolang.mojo.lang.Package getChildren(int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);
      } else {
        return childrenBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder setChildren(
        int index, org.mojolang.mojo.lang.Package value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.set(index, value);
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder setChildren(
        int index, org.mojolang.mojo.lang.Package.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.set(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder addChildren(org.mojolang.mojo.lang.Package value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder addChildren(
        int index, org.mojolang.mojo.lang.Package value) {
      if (childrenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureChildrenIsMutable();
        children_.add(index, value);
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder addChildren(
        org.mojolang.mojo.lang.Package.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder addChildren(
        int index, org.mojolang.mojo.lang.Package.Builder builderForValue) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.add(index, builderForValue.build());
        onChanged();
      } else {
        childrenBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder addAllChildren(
        java.lang.Iterable<? extends org.mojolang.mojo.lang.Package> values) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, children_);
        onChanged();
      } else {
        childrenBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder clearChildren() {
      if (childrenBuilder_ == null) {
        children_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        childrenBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public Builder removeChildren(int index) {
      if (childrenBuilder_ == null) {
        ensureChildrenIsMutable();
        children_.remove(index);
        onChanged();
      } else {
        childrenBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public org.mojolang.mojo.lang.Package.Builder getChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public org.mojolang.mojo.lang.PackageOrBuilder getChildrenOrBuilder(
        int index) {
      if (childrenBuilder_ == null) {
        return children_.get(index);  } else {
        return childrenBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.lang.PackageOrBuilder> 
         getChildrenOrBuilderList() {
      if (childrenBuilder_ != null) {
        return childrenBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(children_);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public org.mojolang.mojo.lang.Package.Builder addChildrenBuilder() {
      return getChildrenFieldBuilder().addBuilder(
          org.mojolang.mojo.lang.Package.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public org.mojolang.mojo.lang.Package.Builder addChildrenBuilder(
        int index) {
      return getChildrenFieldBuilder().addBuilder(
          index, org.mojolang.mojo.lang.Package.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.Package children = 5;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.Package.Builder> 
         getChildrenBuilderList() {
      return getChildrenFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.Package, org.mojolang.mojo.lang.Package.Builder, org.mojolang.mojo.lang.PackageOrBuilder> 
        getChildrenFieldBuilder() {
      if (childrenBuilder_ == null) {
        childrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.lang.Package, org.mojolang.mojo.lang.Package.Builder, org.mojolang.mojo.lang.PackageOrBuilder>(
                children_,
                ((bitField0_ & 0x00000010) == 0x00000010),
                getParentForChildren(),
                isClean());
        children_ = null;
      }
      return childrenBuilder_;
    }

    private java.lang.Object summary_ = "";
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string summary = 10;</code>
     */
    public java.lang.String getSummary() {
      java.lang.Object ref = summary_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        summary_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string summary = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSummaryBytes() {
      java.lang.Object ref = summary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        summary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string summary = 10;</code>
     */
    public Builder setSummary(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      summary_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string summary = 10;</code>
     */
    public Builder clearSummary() {
      
      summary_ = getDefaultInstance().getSummary();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string summary = 10;</code>
     */
    public Builder setSummaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      summary_ = value;
      onChanged();
      return this;
    }

    private org.mojolang.mojo.core.Url repository_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Url, org.mojolang.mojo.core.Url.Builder, org.mojolang.mojo.core.UrlOrBuilder> repositoryBuilder_;
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    public boolean hasRepository() {
      return repositoryBuilder_ != null || repository_ != null;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    public org.mojolang.mojo.core.Url getRepository() {
      if (repositoryBuilder_ == null) {
        return repository_ == null ? org.mojolang.mojo.core.Url.getDefaultInstance() : repository_;
      } else {
        return repositoryBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    public Builder setRepository(org.mojolang.mojo.core.Url value) {
      if (repositoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        repository_ = value;
        onChanged();
      } else {
        repositoryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    public Builder setRepository(
        org.mojolang.mojo.core.Url.Builder builderForValue) {
      if (repositoryBuilder_ == null) {
        repository_ = builderForValue.build();
        onChanged();
      } else {
        repositoryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    public Builder mergeRepository(org.mojolang.mojo.core.Url value) {
      if (repositoryBuilder_ == null) {
        if (repository_ != null) {
          repository_ =
            org.mojolang.mojo.core.Url.newBuilder(repository_).mergeFrom(value).buildPartial();
        } else {
          repository_ = value;
        }
        onChanged();
      } else {
        repositoryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    public Builder clearRepository() {
      if (repositoryBuilder_ == null) {
        repository_ = null;
        onChanged();
      } else {
        repository_ = null;
        repositoryBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    public org.mojolang.mojo.core.Url.Builder getRepositoryBuilder() {
      
      onChanged();
      return getRepositoryFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    public org.mojolang.mojo.core.UrlOrBuilder getRepositoryOrBuilder() {
      if (repositoryBuilder_ != null) {
        return repositoryBuilder_.getMessageOrBuilder();
      } else {
        return repository_ == null ?
            org.mojolang.mojo.core.Url.getDefaultInstance() : repository_;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>.mojo.core.Url repository = 11;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.Url, org.mojolang.mojo.core.Url.Builder, org.mojolang.mojo.core.UrlOrBuilder> 
        getRepositoryFieldBuilder() {
      if (repositoryBuilder_ == null) {
        repositoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.Url, org.mojolang.mojo.core.Url.Builder, org.mojolang.mojo.core.UrlOrBuilder>(
                getRepository(),
                getParentForChildren(),
                isClean());
        repository_ = null;
      }
      return repositoryBuilder_;
    }

    private java.lang.Object license_ = "";
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string license = 12;</code>
     */
    public java.lang.String getLicense() {
      java.lang.Object ref = license_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        license_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string license = 12;</code>
     */
    public com.google.protobuf.ByteString
        getLicenseBytes() {
      java.lang.Object ref = license_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        license_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string license = 12;</code>
     */
    public Builder setLicense(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      license_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string license = 12;</code>
     */
    public Builder clearLicense() {
      
      license_ = getDefaultInstance().getLicense();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>string license = 12;</code>
     */
    public Builder setLicenseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      license_ = value;
      onChanged();
      return this;
    }

    private java.util.List<org.mojolang.mojo.lang.SourceFile> sourceFiles_ =
      java.util.Collections.emptyList();
    private void ensureSourceFilesIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        sourceFiles_ = new java.util.ArrayList<org.mojolang.mojo.lang.SourceFile>(sourceFiles_);
        bitField0_ |= 0x00000100;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.SourceFile, org.mojolang.mojo.lang.SourceFile.Builder, org.mojolang.mojo.lang.SourceFileOrBuilder> sourceFilesBuilder_;

    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.SourceFile> getSourceFilesList() {
      if (sourceFilesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sourceFiles_);
      } else {
        return sourceFilesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public int getSourceFilesCount() {
      if (sourceFilesBuilder_ == null) {
        return sourceFiles_.size();
      } else {
        return sourceFilesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public org.mojolang.mojo.lang.SourceFile getSourceFiles(int index) {
      if (sourceFilesBuilder_ == null) {
        return sourceFiles_.get(index);
      } else {
        return sourceFilesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder setSourceFiles(
        int index, org.mojolang.mojo.lang.SourceFile value) {
      if (sourceFilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSourceFilesIsMutable();
        sourceFiles_.set(index, value);
        onChanged();
      } else {
        sourceFilesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder setSourceFiles(
        int index, org.mojolang.mojo.lang.SourceFile.Builder builderForValue) {
      if (sourceFilesBuilder_ == null) {
        ensureSourceFilesIsMutable();
        sourceFiles_.set(index, builderForValue.build());
        onChanged();
      } else {
        sourceFilesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder addSourceFiles(org.mojolang.mojo.lang.SourceFile value) {
      if (sourceFilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSourceFilesIsMutable();
        sourceFiles_.add(value);
        onChanged();
      } else {
        sourceFilesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder addSourceFiles(
        int index, org.mojolang.mojo.lang.SourceFile value) {
      if (sourceFilesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSourceFilesIsMutable();
        sourceFiles_.add(index, value);
        onChanged();
      } else {
        sourceFilesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder addSourceFiles(
        org.mojolang.mojo.lang.SourceFile.Builder builderForValue) {
      if (sourceFilesBuilder_ == null) {
        ensureSourceFilesIsMutable();
        sourceFiles_.add(builderForValue.build());
        onChanged();
      } else {
        sourceFilesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder addSourceFiles(
        int index, org.mojolang.mojo.lang.SourceFile.Builder builderForValue) {
      if (sourceFilesBuilder_ == null) {
        ensureSourceFilesIsMutable();
        sourceFiles_.add(index, builderForValue.build());
        onChanged();
      } else {
        sourceFilesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder addAllSourceFiles(
        java.lang.Iterable<? extends org.mojolang.mojo.lang.SourceFile> values) {
      if (sourceFilesBuilder_ == null) {
        ensureSourceFilesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sourceFiles_);
        onChanged();
      } else {
        sourceFilesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder clearSourceFiles() {
      if (sourceFilesBuilder_ == null) {
        sourceFiles_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
      } else {
        sourceFilesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public Builder removeSourceFiles(int index) {
      if (sourceFilesBuilder_ == null) {
        ensureSourceFilesIsMutable();
        sourceFiles_.remove(index);
        onChanged();
      } else {
        sourceFilesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public org.mojolang.mojo.lang.SourceFile.Builder getSourceFilesBuilder(
        int index) {
      return getSourceFilesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public org.mojolang.mojo.lang.SourceFileOrBuilder getSourceFilesOrBuilder(
        int index) {
      if (sourceFilesBuilder_ == null) {
        return sourceFiles_.get(index);  } else {
        return sourceFilesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.lang.SourceFileOrBuilder> 
         getSourceFilesOrBuilderList() {
      if (sourceFilesBuilder_ != null) {
        return sourceFilesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sourceFiles_);
      }
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public org.mojolang.mojo.lang.SourceFile.Builder addSourceFilesBuilder() {
      return getSourceFilesFieldBuilder().addBuilder(
          org.mojolang.mojo.lang.SourceFile.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public org.mojolang.mojo.lang.SourceFile.Builder addSourceFilesBuilder(
        int index) {
      return getSourceFilesFieldBuilder().addBuilder(
          index, org.mojolang.mojo.lang.SourceFile.getDefaultInstance());
    }
    /**
     * <pre>
     *&#47;
     * </pre>
     *
     * <code>repeated .mojo.lang.SourceFile source_files = 17;</code>
     */
    public java.util.List<org.mojolang.mojo.lang.SourceFile.Builder> 
         getSourceFilesBuilderList() {
      return getSourceFilesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.lang.SourceFile, org.mojolang.mojo.lang.SourceFile.Builder, org.mojolang.mojo.lang.SourceFileOrBuilder> 
        getSourceFilesFieldBuilder() {
      if (sourceFilesBuilder_ == null) {
        sourceFilesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.lang.SourceFile, org.mojolang.mojo.lang.SourceFile.Builder, org.mojolang.mojo.lang.SourceFileOrBuilder>(
                sourceFiles_,
                ((bitField0_ & 0x00000100) == 0x00000100),
                getParentForChildren(),
                isClean());
        sourceFiles_ = null;
      }
      return sourceFilesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.lang.Package)
  }

  // @@protoc_insertion_point(class_scope:mojo.lang.Package)
  private static final org.mojolang.mojo.lang.Package DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.lang.Package();
  }

  public static org.mojolang.mojo.lang.Package getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Package>
      PARSER = new com.google.protobuf.AbstractParser<Package>() {
    @java.lang.Override
    public Package parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Package(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Package> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Package> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.lang.Package getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

