// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/router.proto

package org.mojolang.mojo.http;

/**
 * Protobuf type {@code mojo.http.Router}
 */
public final class Router extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mojo.http.Router)
    RouterOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Router.newBuilder() to construct.
  private Router(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Router() {
    headers_ = java.util.Collections.emptyList();
    method_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Router();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.mojolang.mojo.http.RouterProto.internal_static_mojo_http_Router_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.mojolang.mojo.http.RouterProto.internal_static_mojo_http_Router_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.mojolang.mojo.http.Router.class, org.mojolang.mojo.http.Router.Builder.class);
  }

  public static final int PATH_FIELD_NUMBER = 1;
  private org.mojolang.mojo.core.TemplateString path_;
  /**
   * <code>.mojo.core.TemplateString path = 1;</code>
   * @return Whether the path field is set.
   */
  @java.lang.Override
  public boolean hasPath() {
    return path_ != null;
  }
  /**
   * <code>.mojo.core.TemplateString path = 1;</code>
   * @return The path.
   */
  @java.lang.Override
  public org.mojolang.mojo.core.TemplateString getPath() {
    return path_ == null ? org.mojolang.mojo.core.TemplateString.getDefaultInstance() : path_;
  }
  /**
   * <code>.mojo.core.TemplateString path = 1;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.core.TemplateStringOrBuilder getPathOrBuilder() {
    return getPath();
  }

  public static final int HEADERS_FIELD_NUMBER = 2;
  private java.util.List<org.mojolang.mojo.http.TemplateHeader> headers_;
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<org.mojolang.mojo.http.TemplateHeader> getHeadersList() {
    return headers_;
  }
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.mojolang.mojo.http.TemplateHeaderOrBuilder> 
      getHeadersOrBuilderList() {
    return headers_;
  }
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  @java.lang.Override
  public int getHeadersCount() {
    return headers_.size();
  }
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.http.TemplateHeader getHeaders(int index) {
    return headers_.get(index);
  }
  /**
   * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
   */
  @java.lang.Override
  public org.mojolang.mojo.http.TemplateHeaderOrBuilder getHeadersOrBuilder(
      int index) {
    return headers_.get(index);
  }

  public static final int METHOD_FIELD_NUMBER = 10;
  private int method_;
  /**
   * <code>.mojo.http.Method method = 10;</code>
   * @return The enum numeric value on the wire for method.
   */
  @java.lang.Override public int getMethodValue() {
    return method_;
  }
  /**
   * <code>.mojo.http.Method method = 10;</code>
   * @return The method.
   */
  @java.lang.Override public org.mojolang.mojo.http.Method getMethod() {
    @SuppressWarnings("deprecation")
    org.mojolang.mojo.http.Method result = org.mojolang.mojo.http.Method.valueOf(method_);
    return result == null ? org.mojolang.mojo.http.Method.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (path_ != null) {
      output.writeMessage(1, getPath());
    }
    for (int i = 0; i < headers_.size(); i++) {
      output.writeMessage(2, headers_.get(i));
    }
    if (method_ != org.mojolang.mojo.http.Method.METHOD_UNSEPECIFIED.getNumber()) {
      output.writeEnum(10, method_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (path_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPath());
    }
    for (int i = 0; i < headers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, headers_.get(i));
    }
    if (method_ != org.mojolang.mojo.http.Method.METHOD_UNSEPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, method_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.mojolang.mojo.http.Router)) {
      return super.equals(obj);
    }
    org.mojolang.mojo.http.Router other = (org.mojolang.mojo.http.Router) obj;

    if (hasPath() != other.hasPath()) return false;
    if (hasPath()) {
      if (!getPath()
          .equals(other.getPath())) return false;
    }
    if (!getHeadersList()
        .equals(other.getHeadersList())) return false;
    if (method_ != other.method_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPath()) {
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
    }
    if (getHeadersCount() > 0) {
      hash = (37 * hash) + HEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getHeadersList().hashCode();
    }
    hash = (37 * hash) + METHOD_FIELD_NUMBER;
    hash = (53 * hash) + method_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.mojolang.mojo.http.Router parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.http.Router parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.http.Router parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.http.Router parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.http.Router parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.mojolang.mojo.http.Router parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.mojolang.mojo.http.Router parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.http.Router parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.http.Router parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.http.Router parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.mojolang.mojo.http.Router parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.mojolang.mojo.http.Router parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.mojolang.mojo.http.Router prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code mojo.http.Router}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mojo.http.Router)
      org.mojolang.mojo.http.RouterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mojolang.mojo.http.RouterProto.internal_static_mojo_http_Router_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mojolang.mojo.http.RouterProto.internal_static_mojo_http_Router_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mojolang.mojo.http.Router.class, org.mojolang.mojo.http.Router.Builder.class);
    }

    // Construct using org.mojolang.mojo.http.Router.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pathBuilder_ == null) {
        path_ = null;
      } else {
        path_ = null;
        pathBuilder_ = null;
      }
      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
      } else {
        headers_ = null;
        headersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      method_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.mojolang.mojo.http.RouterProto.internal_static_mojo_http_Router_descriptor;
    }

    @java.lang.Override
    public org.mojolang.mojo.http.Router getDefaultInstanceForType() {
      return org.mojolang.mojo.http.Router.getDefaultInstance();
    }

    @java.lang.Override
    public org.mojolang.mojo.http.Router build() {
      org.mojolang.mojo.http.Router result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.mojolang.mojo.http.Router buildPartial() {
      org.mojolang.mojo.http.Router result = new org.mojolang.mojo.http.Router(this);
      int from_bitField0_ = bitField0_;
      if (pathBuilder_ == null) {
        result.path_ = path_;
      } else {
        result.path_ = pathBuilder_.build();
      }
      if (headersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          headers_ = java.util.Collections.unmodifiableList(headers_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.headers_ = headers_;
      } else {
        result.headers_ = headersBuilder_.build();
      }
      result.method_ = method_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.mojolang.mojo.http.Router) {
        return mergeFrom((org.mojolang.mojo.http.Router)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.mojolang.mojo.http.Router other) {
      if (other == org.mojolang.mojo.http.Router.getDefaultInstance()) return this;
      if (other.hasPath()) {
        mergePath(other.getPath());
      }
      if (headersBuilder_ == null) {
        if (!other.headers_.isEmpty()) {
          if (headers_.isEmpty()) {
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHeadersIsMutable();
            headers_.addAll(other.headers_);
          }
          onChanged();
        }
      } else {
        if (!other.headers_.isEmpty()) {
          if (headersBuilder_.isEmpty()) {
            headersBuilder_.dispose();
            headersBuilder_ = null;
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000001);
            headersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHeadersFieldBuilder() : null;
          } else {
            headersBuilder_.addAllMessages(other.headers_);
          }
        }
      }
      if (other.method_ != 0) {
        setMethodValue(other.getMethodValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getPathFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 10
            case 18: {
              org.mojolang.mojo.http.TemplateHeader m =
                  input.readMessage(
                      org.mojolang.mojo.http.TemplateHeader.parser(),
                      extensionRegistry);
              if (headersBuilder_ == null) {
                ensureHeadersIsMutable();
                headers_.add(m);
              } else {
                headersBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 80: {
              method_ = input.readEnum();

              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.mojolang.mojo.core.TemplateString path_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.TemplateString, org.mojolang.mojo.core.TemplateString.Builder, org.mojolang.mojo.core.TemplateStringOrBuilder> pathBuilder_;
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     * @return Whether the path field is set.
     */
    public boolean hasPath() {
      return pathBuilder_ != null || path_ != null;
    }
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     * @return The path.
     */
    public org.mojolang.mojo.core.TemplateString getPath() {
      if (pathBuilder_ == null) {
        return path_ == null ? org.mojolang.mojo.core.TemplateString.getDefaultInstance() : path_;
      } else {
        return pathBuilder_.getMessage();
      }
    }
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     */
    public Builder setPath(org.mojolang.mojo.core.TemplateString value) {
      if (pathBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        path_ = value;
        onChanged();
      } else {
        pathBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     */
    public Builder setPath(
        org.mojolang.mojo.core.TemplateString.Builder builderForValue) {
      if (pathBuilder_ == null) {
        path_ = builderForValue.build();
        onChanged();
      } else {
        pathBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     */
    public Builder mergePath(org.mojolang.mojo.core.TemplateString value) {
      if (pathBuilder_ == null) {
        if (path_ != null) {
          path_ =
            org.mojolang.mojo.core.TemplateString.newBuilder(path_).mergeFrom(value).buildPartial();
        } else {
          path_ = value;
        }
        onChanged();
      } else {
        pathBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     */
    public Builder clearPath() {
      if (pathBuilder_ == null) {
        path_ = null;
        onChanged();
      } else {
        path_ = null;
        pathBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     */
    public org.mojolang.mojo.core.TemplateString.Builder getPathBuilder() {
      
      onChanged();
      return getPathFieldBuilder().getBuilder();
    }
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     */
    public org.mojolang.mojo.core.TemplateStringOrBuilder getPathOrBuilder() {
      if (pathBuilder_ != null) {
        return pathBuilder_.getMessageOrBuilder();
      } else {
        return path_ == null ?
            org.mojolang.mojo.core.TemplateString.getDefaultInstance() : path_;
      }
    }
    /**
     * <code>.mojo.core.TemplateString path = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.mojolang.mojo.core.TemplateString, org.mojolang.mojo.core.TemplateString.Builder, org.mojolang.mojo.core.TemplateStringOrBuilder> 
        getPathFieldBuilder() {
      if (pathBuilder_ == null) {
        pathBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.mojolang.mojo.core.TemplateString, org.mojolang.mojo.core.TemplateString.Builder, org.mojolang.mojo.core.TemplateStringOrBuilder>(
                getPath(),
                getParentForChildren(),
                isClean());
        path_ = null;
      }
      return pathBuilder_;
    }

    private java.util.List<org.mojolang.mojo.http.TemplateHeader> headers_ =
      java.util.Collections.emptyList();
    private void ensureHeadersIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        headers_ = new java.util.ArrayList<org.mojolang.mojo.http.TemplateHeader>(headers_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.http.TemplateHeader, org.mojolang.mojo.http.TemplateHeader.Builder, org.mojolang.mojo.http.TemplateHeaderOrBuilder> headersBuilder_;

    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public java.util.List<org.mojolang.mojo.http.TemplateHeader> getHeadersList() {
      if (headersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(headers_);
      } else {
        return headersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public int getHeadersCount() {
      if (headersBuilder_ == null) {
        return headers_.size();
      } else {
        return headersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public org.mojolang.mojo.http.TemplateHeader getHeaders(int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);
      } else {
        return headersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder setHeaders(
        int index, org.mojolang.mojo.http.TemplateHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.set(index, value);
        onChanged();
      } else {
        headersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder setHeaders(
        int index, org.mojolang.mojo.http.TemplateHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.set(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder addHeaders(org.mojolang.mojo.http.TemplateHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
      } else {
        headersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder addHeaders(
        int index, org.mojolang.mojo.http.TemplateHeader value) {
      if (headersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHeadersIsMutable();
        headers_.add(index, value);
        onChanged();
      } else {
        headersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder addHeaders(
        org.mojolang.mojo.http.TemplateHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder addHeaders(
        int index, org.mojolang.mojo.http.TemplateHeader.Builder builderForValue) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.add(index, builderForValue.build());
        onChanged();
      } else {
        headersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder addAllHeaders(
        java.lang.Iterable<? extends org.mojolang.mojo.http.TemplateHeader> values) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, headers_);
        onChanged();
      } else {
        headersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder clearHeaders() {
      if (headersBuilder_ == null) {
        headers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        headersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public Builder removeHeaders(int index) {
      if (headersBuilder_ == null) {
        ensureHeadersIsMutable();
        headers_.remove(index);
        onChanged();
      } else {
        headersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public org.mojolang.mojo.http.TemplateHeader.Builder getHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public org.mojolang.mojo.http.TemplateHeaderOrBuilder getHeadersOrBuilder(
        int index) {
      if (headersBuilder_ == null) {
        return headers_.get(index);  } else {
        return headersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public java.util.List<? extends org.mojolang.mojo.http.TemplateHeaderOrBuilder> 
         getHeadersOrBuilderList() {
      if (headersBuilder_ != null) {
        return headersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(headers_);
      }
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public org.mojolang.mojo.http.TemplateHeader.Builder addHeadersBuilder() {
      return getHeadersFieldBuilder().addBuilder(
          org.mojolang.mojo.http.TemplateHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public org.mojolang.mojo.http.TemplateHeader.Builder addHeadersBuilder(
        int index) {
      return getHeadersFieldBuilder().addBuilder(
          index, org.mojolang.mojo.http.TemplateHeader.getDefaultInstance());
    }
    /**
     * <code>repeated .mojo.http.TemplateHeader headers = 2;</code>
     */
    public java.util.List<org.mojolang.mojo.http.TemplateHeader.Builder> 
         getHeadersBuilderList() {
      return getHeadersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.mojolang.mojo.http.TemplateHeader, org.mojolang.mojo.http.TemplateHeader.Builder, org.mojolang.mojo.http.TemplateHeaderOrBuilder> 
        getHeadersFieldBuilder() {
      if (headersBuilder_ == null) {
        headersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.mojolang.mojo.http.TemplateHeader, org.mojolang.mojo.http.TemplateHeader.Builder, org.mojolang.mojo.http.TemplateHeaderOrBuilder>(
                headers_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        headers_ = null;
      }
      return headersBuilder_;
    }

    private int method_ = 0;
    /**
     * <code>.mojo.http.Method method = 10;</code>
     * @return The enum numeric value on the wire for method.
     */
    @java.lang.Override public int getMethodValue() {
      return method_;
    }
    /**
     * <code>.mojo.http.Method method = 10;</code>
     * @param value The enum numeric value on the wire for method to set.
     * @return This builder for chaining.
     */
    public Builder setMethodValue(int value) {
      
      method_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.Method method = 10;</code>
     * @return The method.
     */
    @java.lang.Override
    public org.mojolang.mojo.http.Method getMethod() {
      @SuppressWarnings("deprecation")
      org.mojolang.mojo.http.Method result = org.mojolang.mojo.http.Method.valueOf(method_);
      return result == null ? org.mojolang.mojo.http.Method.UNRECOGNIZED : result;
    }
    /**
     * <code>.mojo.http.Method method = 10;</code>
     * @param value The method to set.
     * @return This builder for chaining.
     */
    public Builder setMethod(org.mojolang.mojo.http.Method value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      method_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mojo.http.Method method = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethod() {
      
      method_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mojo.http.Router)
  }

  // @@protoc_insertion_point(class_scope:mojo.http.Router)
  private static final org.mojolang.mojo.http.Router DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.mojolang.mojo.http.Router();
  }

  public static org.mojolang.mojo.http.Router getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Router>
      PARSER = new com.google.protobuf.AbstractParser<Router>() {
    @java.lang.Override
    public Router parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Router> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Router> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.mojolang.mojo.http.Router getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

