// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mojo/http/version.proto

package org.mojolang.mojo.http;

public interface VersionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mojo.http.Version)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 major = 1;</code>
   * @return The major.
   */
  int getMajor();

  /**
   * <code>int32 minor = 2;</code>
   * @return The minor.
   */
  int getMinor();
}
